# -*- coding: utf-8

iso_two_to_three = {
    "AF": "AFG",
    "AX": "ALA",
    "AL": "ALB",
    "DZ": "DZA",
    "AS": "ASM",
    "AD": "AND",
    "AO": "AGO",
    "AI": "AIA",
    "AQ": "ATA",
    "AG": "ATG",
    "AR": "ARG",
    "AM": "ARM",
    "AW": "ABW",
    "AU": "AUS",
    "AT": "AUT",
    "AZ": "AZE",
    "BS": "BHS",
    "BH": "BHR",
    "BD": "BGD",
    "BB": "BRB",
    "BY": "BLR",
    "BE": "BEL",
    "BZ": "BLZ",
    "BJ": "BEN",
    "BM": "BMU",
    "BT": "BTN",
    "BO": "BOL",
    "BA": "BIH",
    "BW": "BWA",
    "BV": "BVT",
    "BQ": "BES",
    "BR": "BRA",
    "VG": "VGB",
    "IO": "IOT",
    "BN": "BRN",
    "BG": "BGR",
    "BF": "BFA",
    "BI": "BDI",
    "KH": "KHM",
    "CM": "CMR",
    "CA": "CAN",
    "CV": "CPV",
    "KY": "CYM",
    "CF": "CAF",
    "TD": "TCD",
    "CL": "CHL",
    "CN": "CHN",
    "HK": "HKG",
    "MO": "MAC",
    "CX": "CXR",
    "CC": "CCK",
    "CO": "COL",
    "KM": "COM",
    "CG": "COG",
    "CD": "COD",
    "CK": "COK",
    "CR": "CRI",
    "CI": "CIV",
    "HR": "HRV",
    "CU": "CUB",
    "CY": "CYP",
    "CZ": "CZE",
    "DK": "DNK",
    "DJ": "DJI",
    "DM": "DMA",
    "DO": "DOM",
    "EC": "ECU",
    "EG": "EGY",
    "SV": "SLV",
    "GQ": "GNQ",
    "ER": "ERI",
    "EE": "EST",
    "ET": "ETH",
    "FK": "FLK",
    "FO": "FRO",
    "FJ": "FJI",
    "FI": "FIN",
    "FR": "FRA",
    "GF": "GUF",
    "PF": "PYF",
    "TF": "ATF",
    "GA": "GAB",
    "GM": "GMB",
    "GE": "GEO",
    "DE": "DEU",
    "GH": "GHA",
    "GI": "GIB",
    "GR": "GRC",
    "GL": "GRL",
    "GD": "GRD",
    "GP": "GLP",
    "GU": "GUM",
    "GT": "GTM",
    "GG": "GGY",
    "GN": "GIN",
    "GW": "GNB",
    "GY": "GUY",
    "HT": "HTI",
    "HM": "HMD",
    "VA": "VAT",
    "HN": "HND",
    "HU": "HUN",
    "IS": "ISL",
    "IN": "IND",
    "ID": "IDN",
    "IR": "IRN",
    "IQ": "IRQ",
    "IE": "IRL",
    "IM": "IMN",
    "IL": "ISR",
    "IT": "ITA",
    "JM": "JAM",
    "JP": "JPN",
    "JE": "JEY",
    "JO": "JOR",
    "KZ": "KAZ",
    "KE": "KEN",
    "KI": "KIR",
    "KP": "PRK",
    "KR": "KOR",
    "KW": "KWT",
    "KG": "KGZ",
    "LA": "LAO",
    "LV": "LVA",
    "LB": "LBN",
    "LS": "LSO",
    "LR": "LBR",
    "LY": "LBY",
    "LI": "LIE",
    "LT": "LTU",
    "LU": "LUX",
    "MK": "MKD",
    "MG": "MDG",
    "MW": "MWI",
    "MY": "MYS",
    "MV": "MDV",
    "ML": "MLI",
    "MT": "MLT",
    "MH": "MHL",
    "MQ": "MTQ",
    "MR": "MRT",
    "MU": "MUS",
    "YT": "MYT",
    "MX": "MEX",
    "FM": "FSM",
    "MD": "MDA",
    "MC": "MCO",
    "MN": "MNG",
    "ME": "MNE",
    "MS": "MSR",
    "MA": "MAR",
    "MZ": "MOZ",
    "MM": "MMR",
    "NA": "NAM",
    "NR": "NRU",
    "NP": "NPL",
    "NL": "NLD",
    "AN": "ANT",
    "NC": "NCL",
    "NZ": "NZL",
    "NI": "NIC",
    "NE": "NER",
    "NG": "NGA",
    "NU": "NIU",
    "NF": "NFK",
    "MP": "MNP",
    "NO": "NOR",
    "OM": "OMN",
    "PK": "PAK",
    "PW": "PLW",
    "PS": "PSE",
    "PA": "PAN",
    "PG": "PNG",
    "PY": "PRY",
    "PE": "PER",
    "PH": "PHL",
    "PN": "PCN",
    "PL": "POL",
    "PT": "PRT",
    "PR": "PRI",
    "QA": "QAT",
    "RE": "REU",
    "RO": "ROU",
    "RU": "RUS",
    "RW": "RWA",
    "BL": "BLM",
    "SH": "SHN",
    "KN": "KNA",
    "LC": "LCA",
    "MF": "MAF",
    "PM": "SPM",
    "VC": "VCT",
    "WS": "WSM",
    "SM": "SMR",
    "ST": "STP",
    "SA": "SAU",
    "SN": "SEN",
    "RS": "SRB",
    "SC": "SYC",
    "SL": "SLE",
    "SG": "SGP",
    "SK": "SVK",
    "SI": "SVN",
    "SB": "SLB",
    "SO": "SOM",
    "ZA": "ZAF",
    "GS": "SGS",
    "SS": "SSD",
    "ES": "ESP",
    "LK": "LKA",
    "SD": "SDN",
    "SR": "SUR",
    "SJ": "SJM",
    "SZ": "SWZ",
    "SE": "SWE",
    "SX": "SXM",
    "CH": "CHE",
    "SY": "SYR",
    "TW": "TWN",
    "TJ": "TJK",
    "TZ": "TZA",
    "TH": "THA",
    "TL": "TLS",
    "TG": "TGO",
    "TK": "TKL",
    "TO": "TON",
    "TT": "TTO",
    "TN": "TUN",
    "TR": "TUR",
    "TM": "TKM",
    "TC": "TCA",
    "TV": "TUV",
    "UG": "UGA",
    "UA": "UKR",
    "AE": "ARE",
    "GB": "GBR",
    "US": "USA",
    "UM": "UMI",
    "UY": "URY",
    "UZ": "UZB",
    "VU": "VUT",
    "VE": "VEN",
    "VN": "VNM",
    "VI": "VIR",
    "WF": "WLF",
    "EH": "ESH",
    "YE": "YEM",
    "ZM": "ZMB",
    "ZW": "ZWE"
}

kl_none = {

    "na": "None",
    "need data": "None",
    "needs data": "None",
    "no data": "None",
    "(no data available)": "None",
    "undefined": "None",
    "unknown": "None",
    "unplaced": "None",
    "unrecorded": "None",
    "unspecified": "None",
    "": "None",
    "[no higher geography data]": "None",
    "no higher geography recorded": "None",
    "not applicable": "None",
    "null": "None",
    "nodata": "None",
    "*": "None",
    "no higher geography": "None",
    "no locality data": "None",
    "0": "None",
    "`": "None",
    "-": "None",
    "[]": "None",
    "unknown location": "None",
    "unspecified": "None",
    "not on sheet": "None",
    "unkown": "None",
    "unlisted": "None",
    "uncertain": "None",
    "tbd": "None",
    "state not listed": "None",
    "not given": "None",
    "(not listed)": "None",
    "not readable": "None",
    "none": "None",
    "[none]": "None",
    "[illegible]": "None",

}

kl = {
    "continent": {
        u"eurasia": "asia",
        u"africa, asia ?": "asia",
        u"southeast asia": "asia",
        u"asia?": "asia",
        u"asia (?)": "asia",
        u"asia ?": "asia",
        u"africa?": "africa",
        u"africa/asia?": "asia",
        u"s. w. africa": "africa",
        u"south east asia": "asia",
        u"neotropical / south america": "south america",
        u"west africa": "africa",
        u"[asia]": "asia",
        u"australian": "australia",
        u"east central africa": "africa",
        u"east coast africa": "africa",
        u"west coast africa": "africa",
        u"indoaustralia": "australia",
        u"european seas": "europe",
        u"asiape": "asia",
        u"asia/pacific ocean": "asia",
        u"south america?": "south america",
        u"e. africa": "africa",
        u"australia (continent)": "australia",
        u"europe (?)": "europe",
        u"asia/indoaustralia?": "asia",
        u"east africa": "africa",
        u"north america?": "north america",
        u"south america ?": "south america",
        u"europe?": "europe",
        u"asia minor": "asia",
        u"north america (?)": "north america",
        u"australasia": "asia",
        u"indoaustralia?": "australia",
        u"asia?indies": "asia",
        u"african": "africa",
        u"africa (?)": "africa",
        u"s. america": "south america",
        u"north and central america": "north america",
        u"middle east": "asia",
        u"n. america": "north america",
        u"madagascar": "africa",
        u"cental america": "north america",
        u"central america": "north america",
        u"central america?": "north america",
        u"afica": "africa",
        u"afirca": "africa",
        u"africa, asia": "asia",
        u"africa/asia": "asia",
        u"africa ()": "africa",
        u"asia ()": "asia",
        u"europe ()": "europe",
        u"asiaindies": "asia",
        u"asia/indoaustralia": "asia",
        u"north america ()": "north america",
        u"afrotropical": "africa",
        u"neotropical": "south america",
        u"neotropical / central america": "north america",
        u"oriental": "asia",

        u"[pacific ocean": "pacific ocean",
        u"pacific ocean": "pacific ocean",
        u"south indian ocean": "indian ocean",
        u"indo pacific": "pacific ocean",
        u"eastern atlantic": "atlantic ocean",
        u"indian & n pacific": "indian ocean",
        u"south pacific ocean": "pacific ocean",
        u"indian ocean (probably)": "indian ocean",
        u"arctic region": "arctic ocean",
        u"north indian ocean": "indian ocean",
        u"w. pacific": "pacific ocean",
        u"n. w. atlantic": "atlantic ocean",
        u"indo-pacific": "pacific ocean",
        u"sw atlantic": "atlantic ocean",
        u"southwestern pacific": "pacific ocean",
        u"indian ocean, eastern": "indian ocean",
        u"north pacific": "pacific ocean",
        u"western atlantic": "atlantic ocean",
        u"central pacific": "pacific ocean",
        u"s. w. pacific": "pacific ocean",
        u"n. atlantic": "atlantic ocean",
        u"south atlantic": "atlantic ocean",
        u"western indian ocean": "indian ocean",
        u"indian ocean, western": "indian ocean",
        u"mediterranean/atl": "mediterranean sea",
        u"northern atlantic": "atlantic ocean",
        u"indian ocean": "indian ocean",
        u"antartic-pacific": "pacific ocean",
        u"mediterranean sea": "mediterranean sea",
        u"caribbean ocean": "caribbean sea",
        u"nw & central pacific": "pacific ocean",
        u"s. atlantic": "atlantic ocean",
        u"se pacific": "pacific ocean",
        u"south atlantic ocean": "atlantic ocean",
        u"eastern north atlantic": "atlantic ocean",
        u"west indian ocean": "indian ocean",
        u"se atlantic": "atlantic ocean",
        u"north atlantic": "atlantic ocean",
        u"atlantic, western central": "atlantic ocean",
        u"north atlantic ocean": "atlantic ocean",
        u"ne pacific": "pacific ocean",
        u"east pacific ocean": "pacific ocean",
        u"e. tropical pacific": "pacific ocean",
        u"indo-pacific ocean": "pacific ocean",
        u"arctic ocean": "arctic ocean",
        u"indo-west pacific": "pacific ocean",
        u"s. pacific": "pacific ocean",
        u"southern pacific": "pacific ocean",
        u"nearctic": "arctic ocean",
        u"atlantic ocean": "atlantic ocean",
        u"west pacific": "pacific ocean",
        u"eastern pacific": "pacific ocean",
        u"south pacific": "pacific ocean",
        u"western pacific": "pacific ocean",
        u"atlantic islands": "atlantic ocean",
        u"atlantic/pacific": "atlantic ocean",
        u"pacific/indian ocean": "indian ocean",
        u"north pacific ocean": "pacific ocean",
        u"palearctic": "arctic ocean",
        u"east mediterranean sea": "mediterranean sea",
        u"nw atlantic": "atlantic ocean",
        u"pacific islands": "pacific ocean",
        u"ne atlantic": "atlantic ocean",
        u"caribbean sea": "caribbean sea",

        u"windward island": "north america",
        u"windward islands": "north america",
        u"pacifuc": "pacific ocean",
        u"wst indies": "north america",
        u"pacifc ocean": "pacific ocean",
        u"caribbean": "caribbean sea",
        u"carribbean": "caribbean sea",
        u"indian": "indian ocean",
        u"pasific": "pacific ocean",
        u"carribbean sea": "caribbean sea",
        u"caribbenan": "caribbean sea",
        u"behring sea": "bering sea",
        u"mediterranea sea": "mediterranean sea",
        u"mediteranean sea": "mediterranean sea",
        u"west indied": "north america",
        u"weat indies": "north america",
        u"west indies": "north america",
        u"carribean": "caribbean sea",
        u"caribean": "caribbean sea",
        u"indean ocean": "indian ocean",
        u"atlantic": "atlantic ocean",
        u"pacific": "pacific ocean",
        u"indian": "indian ocean",
        u"caribbean": "caribbean sea",
        u"mediterranean": "mediterranean sea",
        u"antarctic": "antarctic ocean",
        u"arctic": "arctic ocean",
        u"antartica": "antarctica",
        u"southern": "antarctic ocean",
        u"southern ocean": "antarctic ocean",
    },

    "country": {
        u"usa": "united states",
        u"u.s.a.": "united states",
        u"united states of america": "united states",
        u"united sa": "united states",
        u"united sates": "united states",
        u"united stae": "united states",
        u"united staes": "united states",
        u"united state": "united states",
        u"united stated": "united states",
        u"us": "united states",
        u"u.s.": "united states",
        u"?usa": "united states",
        u"[u.s.a.]": "united states",
        u"[usa]": "united states",
        u"u s a": "united states",
        u"u.s.a": "united states",
        u"u.s.a,": "united states",
        u"u.s.a..": "united states",
        u"usa,": "united states",
        u"usa?": "united states",
        u"usa.": "united states",
        u"united stats": "united states",
        u"united ststes": "united states",
        u"unites states": "united states",
        u"unite states": "united states",
        u"united  states": "united states",
        u"united states (?)": "united states",
        u"united states?": "united states",
        u"united_states": "united states",

        u"republich of seychelles": "seychelles",
        u"burundi/zaire": "burundi",
        u"maldives islands": "maldives",
        u"uganda/democratic republic of congo": "congo, the democratic republic of the",
        u"belgian congo": "congo",
        u"united kingdom of great britain and northern ireland": "united kingdom",
        u"ireland, republic of": "ireland",
        u"austria/hungary": "hungary",
        u"[east africa], tanganyika [tanzania]": "tanzania",
        u"seychelles republic": "seychelles",
        u"uganda-kenya": "uganda",
        u"india/nepal": "nepal",
        u"dominican republoic": "dominican republic",
        u"germaniae [germany]": "germany",
        u"[kiribati].": "kiribati",
        u"hispaniola (dom.r.+ haiti)": "haiti",
        u"federal republic germany": "germany",
        u"czech republic/germany/poland": "czech republic",
        u"schlesien [poland]": "poland",
        u"egypt/sudan": "egypt",
        u"zambia/zimbabwe": "zambia",
        u"russia/china": "china",
        u"bolivia, peru": "peru",
        u"cameroon/nigeria": "nigeria",
        u"french antilles (guedeloupe, martinique & al.)": "martinique",
        u"bolivia/peru": "peru",
        u"laos/thailand": "thailand",
        u"[austria]": "austria",
        u"malawi (nyasaland)": "malawi",
        u"republic of the philippines": "philippines",
        u"northern new zealand": "new zealand",
        u"kingdom of norway": "norway",
        u"republic of marshall islands": "marshall islands",
        u"liberia/ghana": "ghana",
        u"palau island": "palau",
        u"[uruguay]": "uruguay",
        u"samoan islands": "samoa",
        u"egypt/morocco": "egypt",
        u"panama/united states": "panama",
        u"republic of croatia": "croatia",
        u"kenya/uganda": "uganda",
        u"spanish morocco": "morocco",
        u"armenia/azerbaijan/georgia/russia": "azerbaijan",
        u"france/switzerland": "switzerland",
        u"saudi arabia/yemen/oman": "oman",
        u"central siam, thailand": "thailand",
        u"mexico, united states": "united states",
        u"bangladesh/india": "bangladesh",
        u"[brazil]": "brazil",
        u"united states and canada": "united states",
        u"togo or liberia": "togo",
        u"maldives.": "maldives",
        u"republic of kiribati": "kiribati",
        u"[united kingdom]": "united kingdom",
        u"faroe islands.": "faroe islands",
        u"republic of senegal": "senegal",
        u"burma [myanmar]": "myanmar",
        u"india, nepal": "nepal",
        u"mongolia [=kazakhstan]": "mongolia",
        u"mexico/central america": "mexico",
        u"republic of malta": "malta",
        u"france/spain": "france",
        u"[croatia]": "croatia",
        u"kingdom of denmark": "denmark",
        u"uzbekistan [turkestania]": "uzbekistan",
        u"china [zhonghua]": "china",
        u"austria / italy": "austria",
        u"east siam, thailand": "thailand",
        u"west australia": "australia",
        u"malaysia/philippines": "philippines",
        u"republic of the marshall islands": "marshall islands",
        u"israel ()": "israel",
        u"namibia/south africa": "namibia",
        u"guatemala city": "guatemala",
        u"[cayman islands]": "cayman islands",
        u"syria or lebanon": "lebanon",
        u"central africa, congo [zaire]": "congo",
        u"iran/pakistan": "iran",
        u"republic of india": "india",
        u"zaire/uganda": "uganda",
        u"bangladesh, india": "bangladesh",
        u"dominican republic": "dominican republic",
        u"aruba.": "aruba",
        u"post of spain": "spain",
        u"french guyana": "french guiana",
        u"south india": "india",
        u"suecia [sweden]": "sweden",
        u"independent state of samoa": "samoa",
        u"south cook islands": "cook islands",
        u"rwanda/uganda": "rwanda",
        u"west indies [=trinidad and tobago]": "trinidad and tobago",
        u"east siam [=thailand]": "thailand",
        u"central china": "china",
        u"kenya/tanzania": "tanzania",
        u"[chile ]": "chile",
        u"india & iran": "iran",
        u"[british guiana (guyana)]": "guyana",
        u"turkey (label says \"t\u00fcrkei\"": "turkey",
        u"rep. south africa": "south africa",
        u"ireland (\u00e9ire)": "ireland",
        u"syria/lebanon": "lebanon",
        u"[kyrgyzstan]": "kyrgyzstan",
        u"mexico/el salvador": "mexico",
        u"congo, the democratic republic of the": "congo, the democratic republic of the",
        u"jordan/israel": "israel",
        u"ecuador-galapagos islands": "ecuador",
        u"india/pakistan/china": "china",
        u"senegal/mali": "senegal",
        u"kenya/tanzania/zanzibar": "tanzania",
        u"new zealand.": "new zealand",
        u"state of israel": "israel",
        u"france/spain/sweden/netherlands//united kingdom": "united kingdom",
        u"democratic republic of the congo": "congo, the democratic republic of the",
        u"british north borneo [malaysia]": "malaysia",
        u"germany/switzerland": "switzerland",
        u"armenia/azerbaijan/georgia": "azerbaijan",
        u"camerunia [= cameroon]": "cameroon",
        u"fr.-indo china": "china",
        u"burma/myanmar": "myanmar",
        u"japan/korea/vietnam": "japan",
        u"cayman islands.": "cayman islands",
        u"cayenne [=french guiana]": "french guiana",
        u"colombia ()": "colombia",
        u"martinique.": "martinique",
        u"guatemala/belize": "guatemala",
        u"[central africa], congo [zaire]": "congo, the democratic republic of the",
        u"united states - minor outlying is.": "united states minor outlying islands",
        u"bahamas ids": "bahamas",
        u"[jamaica]": "jamaica",
        u"south sudan": "sudan",
        u"[germany]": "germany",
        u"russian federation (former u.s.s.r.": "russian federation",
        u"siam [thailand]": "thailand",
        u"republic of niger": "niger",
        u"palau & federated states of micronesia": "palau",
        u"singapore/china": "china",
        u"indonesia/malaysia": "malaysia",
        u"mexico  mexico": "mexico",
        u"syria [jordan]": "jordan",
        u"republic of cuba": "cuba",
        u"spain (espa\u00f1a)": "spain",
        u"myanmar (burma)": "myanmar",
        u"saudi arabia (arabia)": "saudi arabia",
        u"guyana batava [surinam]": "suriname",
        u"russia [finland prior to 1940]": "russian federation",
        u"east germany": "germany",
        u"malawi/madagascar": "malawi",
        u"dem. rep. of congo": "congo, the democratic republic of the",
        u"[puerto rico]": "puerto rico",
        u"republica dominicana": "dominican republic",
        u"congo republic": "congo, the democratic republic of the",
        u"panama, boca del toro": "panama",
        u"leeward islands: guadeloupe": "guadeloupe",
        u"mexico/united states": "united states",
        u"persia (iran)": "iran",
        u"[south africa]": "south africa",
        u"kingdom of tonga": "tonga",
        u"lebanon or syria": "lebanon",
        u"samoan ids.": "samoa",
        u"montenegro (crna gora)": "montenegro",
        u"united states minor outlying islands": "united states minor outlying islands",
        u"pelew islands [=palau]": "palau",
        u"guyana [as british guiana on the packet]": "guyana",
        u"peninsular malaysia": "malaysia",
        u"dem. rep. congo": "congo, the democratic republic of the",
        u"germany [poland]": "germany",
        u"[england (united kingdom)]": "united kingdom",
        u"namibia (swa)": "namibia",
        u"libyan arab jamahiriya": "libya",
        u"russia, kazakhstan": "kazakhstan",
        u"europe [probably now poland]": "poland",
        u"malawi/mozambique/zimbabwe": "mozambique",
        u"sri lanka (ceylon)": "sri lanka",
        u"neth. ant./guadeloupe": "guadeloupe",
        u"jordan/isreal": "jordan",
        u"panama ()": "panama",
        u"wallis and futuna islands": "wallis and futuna",
        u"georgia - republic of": "georgia",
        u"uganda/kenya": "uganda",
        u"republic of nicaragua": "nicaragua",
        u"western sahara.": "western sahara",
        u"the marshall islands": "marshall islands",
        u"england/france/spain": "france",
        u"brazil and zanzibar": "brazil",
        u"federal republic of germany": "germany",
        u"east malaysia": "malaysia",
        u"palau.": "palau",
        u"czech republic & slovakia": "czech republic",
        u"[venezuela]": "venezuela",
        u"south africa/swaziland": "swaziland",
        u"mexico/costa rica": "mexico",
        u"honduras/guatemala/costa rica": "guatemala",
        u"australia (country)": "australia",
        u"malaysia/singapore": "malaysia",
        u"petite martinique": "martinique",
        u"republic of guinea": "guinea",
        u"guam island": "guam",
        u"southern cook islands": "cook islands",
        u"federative republic of brazil": "brazil",
        u"e. malaysia": "malaysia",
        u"east greenland": "greenland",
        u"brazil/colombia": "brazil",
        u"republic of the congo": "congo, the democratic republic of the",
        u"russia [=kazakhstan]": "kazakhstan",
        u"people's republic of china": "china",
        u"congo-kinshasa": "congo, the democratic republic of the",
        u"british indian ocean territory ocean territory": "british indian ocean territory",
        u"republic of costa rica": "costa rica",
        u"vanuatu id": "vanuatu",
        u"central africa, congo": "congo",
        u"argentina/patagonia": "argentina",
        u"persien [=iran]": "iran",
        u"republic of ecuador": "ecuador",
        u"[angola]": "angola",
        u"western ireland": "ireland",
        u"republic of colombia": "colombia",
        u"bahamas, the": "bahamas",
        u"bhutan/india": "bhutan",
        u"north vietnam/china": "china",
        u"argentina/uruguay": "argentina",
        u"china/mongolia/russia": "mongolia",
        u"arabia [=jordan]": "jordan",
        u"congo (brazzaville)": "congo, the democratic republic of the",
        u"w. jamaica": "jamaica",
        u"palestine [=jordan]": "jordan",
        u"chile/peru": "peru",
        u"[dominican republic]": "dominican republic",
        u"tonga island": "tonga",
        u"dominican rep.": "dominica",
        u"w brazil, e peru, e ecuador": "brazil",
        u"republic of south africa": "south africa",
        u"republic of botswana": "botswana",
        u"dominica, lesser antilles": "dominica",
        u"(hungary)": "hungary",
        u"guatemala, mexico": "guatemala",
        u"thailand.": "thailand",
        u"cook islands.": "cook islands",
        u"republic of madagascar": "madagascar",
        u"united states/canada": "united states",
        u"martinique id.": "martinique",
        u"paraguay or argentina": "argentina",
        u"china/japan": "japan",
        u"iran (persia)": "iran",
        u"greenland (self-governing danish territory)": "greenland",
        u"[argentina]": "argentina",
        u"bahamas ids.": "bahamas",
        u"[indonesia]": "indonesia",
        u"russia [=ukraine]": "ukraine",
        u"china, people's republic of": "china",
        u"guadeloupe.": "guadeloupe",
        u"northern ireland": "ireland",
        u"israel/lebanon/syria/turkey": "lebanon",
        u"tunisian republic": "tunisia",
        u"paraguayq": "paraguay",
        u"western taiwan": "taiwan",
        u"[kiribati]": "kiribati",
        u"mexico/costa rica/panama": "panama",
        u"[spain]": "spain",
        u"republic of haiti": "haiti",
        u"the gambia": "gambia",
        u"british solomon islands": "solomon islands",
        u"congo, democratic republic of": "congo, the democratic republic of the",
        u"ireland/eire": "ireland",
        u"czechoslavakia/germany/*": "germany",
        u"taiwan (= republic of china)": "taiwan",
        u"wales, united kingdom": "united kingdom",
        u"united states, canada": "united states",
        u"serbia/montenegro": "serbia",
        u"brasilia meridionali [c. brazil]": "brazil",
        u"republic of ireland": "ireland",
        u"[costa rica]": "costa rica",
        u"prusia [germany]": "germany",
        u"germany (west)": "germany",
        u"palestine/israel": "israel",
        u"dominican republic/puerto rico": "puerto rico",
        u"tuvalu.": "tuvalu",
        u"colombia, ecuador": "colombia",
        u"palestine [jordan]": "jordan",
        u"[central africa], congo fran\u008daise": "congo",
        u"republic of liberia": "liberia",
        u"w, n brazil, n peru, ecuador": "brazil",
        u"palestine/lebanon": "lebanon",
        u"french guiana & braz": "french guiana",
        u"austria(=hungary)": "hungary",
        u"czech republic (used to be in germany)": "czech republic",
        u"argentina/paraguay": "argentina",
        u"abyssinia [ethiopia]": "ethiopia",
        u"vanuatu (new hebrides)": "vanuatu",
        u"russian turkestan [=kyrgyzstan]": "kyrgyzstan",
        u"saudi arabia.": "saudi arabia",
        u"republic of trinidad and tobago": "trinidad and tobago",
        u"congo, dem. rep. of the": "congo, the democratic republic of the",
        u"peoples republic of china": "china",
        u"macedonia, the former yugoslav republic of": "macedonia",
        u"ecuador or peru": "peru",
        u"juan fernandez islands (administrative division of chile)": "chile",
        u"cambodia/vietnam": "cambodia",
        u"persia [=iran]": "iran",
        u"tanzania/uganda": "tanzania",
        u"palestine [=israel]": "israel",
        u"dalmatia [croatia]": "croatia",
        u"philippines.": "philippines",
        u"vanuatu.": "vanuatu",
        u"turkestan/uzbekistan": "uzbekistan",
        u"europe, now poland": "poland",
        u"kenya-tanzania-uganda": "tanzania",
        u"republic of maldives": "maldives",
        u"cambodia/thailand/vietnam": "cambodia",
        u"lower austria": "austria",
        u"mozambique channel isl": "mozambique",
        u"belgium/switzerland": "belgium",
        u"united states of colombia": "united states",
        u"southern france": "france",
        u"russian federation (former u.s.s.r.)": "russian federation",
        u"[thailand]": "thailand",
        u"republic of palau": "palau",
        u"commonwealth of the northern mariana islands": "northern mariana islands",
        u"senegal to e. democratic republic of congo; bioko (equatorial guinea)": "senegal",
        u"pakistan  and baluchistan": "pakistan",
        u"the netherlands": "netherlands",
        u"republic of peru": "peru",
        u"[jordan]": "jordan",
        u"[france]": "france",
        u"brazil []": "brazil",
        u"caucasia [=ukraine]": "ukraine",
        u"[ukraine]": "ukraine",
        u"madeira (portugal)": "portugal",
        u"palau ids.": "palau",
        u"vanuatu(new hebrides)": "vanuatu",
        u"thailand [siam]": "thailand",
        u"commonwealth of dominica": "dominica",
        u"canada and united states": "united states",
        u"montserrat.": "montserrat",
        u"east nepal": "nepal",
        u"congo, democratic republic of the": "congo, the democratic republic of the",
        u"mexico/nicaragua": "nicaragua",
        u"england/denmark/ireland/peru/united states": "denmark",
        u"argentina/brazil/paraguay": "argentina",
        u"lower cook islands": "cook islands",
        u"angola/namibia/south africa": "namibia",
        u"neth. antil./guadeloupe": "guadeloupe",
        u"tanzania, united republic of": "tanzania",
        u"congo, democratic republic of zaire": "congo, the democratic republic of the",
        u"siam [=thailand]": "thailand",
        u"czech republic/poland": "czech republic",
        u"[poland]": "poland",
        u"norfolk islands": "norfolk island",
        u"guadeloupe island": "guadeloupe",
        u"tanzania/madagascar": "tanzania",
        u"argentina/colombia/peru": "argentina",
        u"cura\u00e7ao/jamaica": "jamaica",
        u"chile/patagonia": "chile",
        u"samoa.": "samoa",
        u"taiwan, province of china": "taiwan",
        u"england/france": "france",
        u"guiana [guyana]": "guyana",
        u"n. cook islands": "cook islands",
        u"french west indies [france]": "france",
        u"south yemen": "yemen",
        u"montserrat island": "montserrat",
        u"germany/poland": "germany",
        u"caucasus [=ukraine]": "ukraine",
        u"\"austria\"": "austria",
        u"republic of serbia": "serbia",
        u"saudi arabia/oman": "oman",
        u"bohemica [= czechoslovakia]": "slovakia",
        u"togo or ghana": "togo",
        u"jamaica/st. croix": "jamaica",
        u"ferghana [=kyrgyzstan]": "kyrgyzstan",
        u"afghanistan/iran/pakistan": "afghanistan",
        u"republic of nauru": "nauru",
        u"india/pakistan": "pakistan",
        u"[vanuatu]": "vanuatu",
        u"the dominican republic": "dominican republic",
        u"islamic republic of iran": "iran",
        u"[canada]": "canada",
        u"cochin-china": "china",
        u"peru/brazil": "brazil",
        u"saudi arabia/yemen": "saudi arabia",
        u"congo dr": "congo, the democratic republic of the",
        u"rhodesia [zimbabwe]": "zimbabwe",
        u"sachsen [germany]": "germany",
        u"argentina, chile": "argentina",
        u"lebanon.": "lebanon",
        u"[new zealand]": "new zealand",
        u"west indies [=trindiad and tobago]": "india",
        u"iran (label says \"persia\")": "iran",
        u"muscat/oman/saudi arabia": "oman",
        u"iran/turkmenistan": "turkmenistan",
        u"south thailand, malaysia peninsula": "malaysia",
        u"british honduras [belize]": "belize",
        u"ghana & togo": "togo",
        u"gambia/guinea/senegal": "senegal",
        u"austria-italy": "austria",
        u"[central africa], congo": "congo",
        u"costa rica, panama": "panama",
        u"zambia, zimbabwe": "zambia",
        u"republic of sierra leone": "sierra leone",
        u"burma (myanmar)": "myanmar",
        u"new hebrides (vanuatu)": "vanuatu",
        u"argentina/suriname/venezuela": "argentina",
        u"north germany": "germany",
        u"serbia and montenegro": "serbia",
        u"new hebrides [=vanuatu]": "vanuatu",
        u"colombia/suriname": "colombia",
        u"singapore/thailand": "thailand",
        u"[central africa, congo]": "congo",
        u"[india]": "india",
        u"democratic republic of congo/republic of congo/rwanda": "congo, the democratic republic of the",
        u"portuguese east africa (mozambique)": "mozambique",
        u"congo/rwanda/zimbabwe": "congo",
        u"united states ()": "united states",
        u"bermuda (uk overseas territory)": "bermuda",
        u"belgian congo [democratic republic of the congo]": "congo, the democratic republic of the",
        u"zambia (northern rhodesia)": "zambia",
        u"bolivia, plurinational state of": "bolivia",
        u"republic of panama": "panama",
        u"mexico/guatemala": "guatemala",
        u"fiji island/s": "fiji",
        u"bahamas islands": "bahamas",
        u"south africa, republic of": "south africa",
        u"guam (us unincorporated territory)": "guam",
        u"costa rica/nicaragua": "nicaragua",
        u"congo/rwanda/zaire": "congo, the democratic republic of the",
        u"republic of georgia": "georgia",
        u"formosa [taiwan]": "taiwan",
        u"republic of hungary": "hungary",
        u"bolivia/french guiana/suriname/venezuela": "french guiana",
        u"georgia (russia)": "georgia",
        u"[ethiopia]": "ethiopia",
        u"bolivia/guyana/paraguay": "bolivia",
        u"kingdom of the netherlands": "netherlands",
        u"mauritius island/s": "mauritius",
        u"afghanistan/china/ussr": "afghanistan",
        u"people's democratic republic of algeria": "algeria",
        u"new holland [=australia]": "australia",
        u"commonwealth of the bahamas": "bahamas",
        u"congo [zaire]": "congo, the democratic republic of the",
        u"spain (overseas territory)": "spain",
        u"northwest persia [=iran]": "iran",
        u"republic of turkey": "turkey",
        u"turkmenistan, uzbekistan": "uzbekistan",
        u"[paraguay]": "paraguay",
        u"puerto rico (us)": "puerto rico",
        u"north persia [=iran]": "iran",
        u"brazil/paraguay": "brazil",
        u"west pakistan": "pakistan",
        u"dominica, british west indies": "dominica",
        u"republic of fiji islands": "fiji",
        u"costa rica/colombia": "colombia",
        u"lapland/norway": "norway",
        u"kiribati (gilbert islands)": "kiribati",
        u"latvia/estonia": "latvia",
        u"polynesia [=tuvalu]": "tuvalu",
        u"lebanon/syria": "lebanon",
        u"poland [silesia]": "poland",
        u"georgia (former u.r.s.s,known as u.s.s.r.)": "georgia",
        u"colombia/peru": "peru",
        u"[east africa], uganda": "uganda",
        u"east thailand": "thailand",
        u"(french (indo-china)": "china",
        u"south georgia": "south georgia and the south sandwich islands",
        u"bosnia and herzegovina/croatia": "croatia",
        u"french guiana,": "french guiana",
        u"[surinam (suriname)]": "suriname",
        u"brasilia [brazil]": "brazil",
        u"grand cayman islands": "cayman islands",
        u"[israel]": "israel",
        u"french guiana (france)": "french guiana",
        u"thailand (siam)": "thailand",
        u"french polynesia [tahiti]": "french polynesia",
        u"republic of finland": "finland",
        u"france or switzerland": "switzerland",
        u"canada.": "canada",
        u"canada/united states": "united states",
        u"dem. republic of the congo": "congo, the democratic republic of the",
        u"seychelles island": "seychelles",
        u"west indies [trinidad and tobago]": "trinidad and tobago",
        u"[panama]": "panama",
        u"austria, hungary": "hungary",
        u"panamas": "panama",
        u"abkhazia (georgia)": "georgia",
        u"republic of zambia": "zambia",
        u"dominican republic/jamaica/trinidad and tobago": "jamaica",
        u"[italy]": "italy",
        u"russian poland": "poland",
        u"china/india/sri lanka": "sri lanka",
        u"cyprus/switzerland": "cyprus",
        u"guyana [british guiana]": "guyana",
        u"west indies (cuba)": "cuba",
        u"republic of france": "france",
        u"samoa and american samoa": "samoa",
        u"saint pierre and miquelon (french territorial collectivity)": "saint pierre and miquelon",
        u"malaysia, new guinea, etc.": "malaysia",
        u"france & switzerland": "switzerland",
        u"kamerun [= cameroon]": "cameroon",
        u"kingdom of belgium": "belgium",
        u"republic of kenya": "kenya",
        u"pitcairn's island.": "pitcairn",
        u"zambia (n. rhodesia)": "zambia",
        u"congo to kenya": "congo",
        u"indian ocean island/s": "india",
        u"oriental republic of uruguay": "uruguay",
        u"western uganda": "uganda",
        u"india/sri lanka": "sri lanka",
        u"india.": "india",
        u"gibraltar (uk overseas territory)": "gibraltar",
        u"uzbekistan (russa)": "uzbekistan",
        u"denmark(zealand)": "denmark",
        u"saudi arabia()": "saudi arabia",
        u"syria [israel]": "israel",
        u"federated states of micronesia/palau": "palau",
        u"venezuela, bolivarian republic of": "venezuela",
        u"yemen, saudi arabia": "saudi arabia",
        u"pakistan or india": "pakistan",
        u"bermuda island/s": "bermuda",
        u"northeast persia [=iran]": "iran",
        u"mozambique/zanzibar": "mozambique",
        u"mesopotamia [=iraq]": "iraq",
        u"\"hungary\"": "hungary",
        u"south africa/zimbabwe": "south africa",
        u"cuba/trinidad and tobago": "cuba",
        u"egypt, sudan": "egypt",
        u"ceylon [sri lanka]": "sri lanka",
        u"sudan/uganda": "uganda",
        u"republic of poland": "poland",
        u"north siam [=thailand]": "thailand",
        u"malaysia/thailand": "malaysia",
        u"gallia [france]": "france",
        u"commonwealth of australia": "australia",
        u"ecuador/peru": "peru",
        u"turkestan [=kyrgyzstan]": "kyrgyzstan",
        u"portuguese east africa [now mozambique]": "mozambique",
        u"indonesia.": "indonesia",
        u"[samoa]": "samoa",
        u"tanganyika [tanzania], africa": "tanzania",
        u"[french guiana]": "french guiana",
        u"new zealand  (country not listed)": "new zealand",
        u"iran, islamic republic of": "iran",
        u"[mexico]": "mexico",
        u"honduras []": "honduras",
        u"[philippines]": "philippines",
        u"jamaica ()": "jamaica",
        u"northern rhodesia [zambia]": "zambia",
        u"argentina/brazil/uruguay": "argentina",
        u"american samoa (us)": "american samoa",
        u"south manchuria [=china]": "china",
        u"australia/new zealand": "new zealand",
        u"siam, thailand": "thailand",
        u"crimea [=ukraine]": "ukraine",
        u"england/france/ireland": "france",
        u"republic of iraq": "iraq",
        u"syria [=jordan]": "jordan",
        u"british guiana [guyana]": "guyana",
        u"australia, captive": "australia",
        u"grenada/guadeloupe/navassa/netherland antilles": "guadeloupe",
        u"martinique (france)": "france",
        u"estonia/latvia": "latvia",
        u"bahamas [=turks and caicos islands]": "bahamas",
        u"malaysia timor": "malaysia",
        u"burma/thailand": "thailand",
        u"mongolia/russia": "mongolia",
        u"colombia, panama": "panama",
        u"niue island": "niue",
        u"israel/jordan": "israel",
        u"tanzania (united republic of tanzania, formerly the united repub": "tanzania",
        u"fiji islands": "fiji",
        u"[palau]": "palau",
        u"[australia]": "australia",
        u"british east africa [= kenya]": "kenya",
        u"republic_of_nicaragua": "nicaragua",
        u"pitcairn island].": "pitcairn",
        u"iceland/greenland": "iceland",
        u"greenland (denmark)": "greenland",
        u"angola/namibia": "namibia",
        u"taiwan or indonesia": "taiwan",
        u"bermudas": "bermuda",
        u"grenada & grenadines": "grenada",
        u"polynesia [=kiribati]": "kiribati",
        u"northwestern taiwan": "taiwan",
        u"france/italy": "france",
        u"kenya/uganda/tanzania": "tanzania",
        u"guadeloupe (france)": "guadeloupe",
        u"swa-namibia": "namibia",
        u"[guatemala]": "guatemala",
        u"thailand (french indo-china)": "china",
        u"colombia/ecuador": "colombia",
        u"ceylon [= sri lanka]": "sri lanka",
        u"west indies [=cayman islands]": "cayman islands",
        u"kiribati.": "kiribati",
        u"norfolk island (australia)": "australia",
        u"france/scandinavia/united kingdom": "united kingdom",
        u"myanmar-thailand": "thailand",
        u"persia [iran]": "iran",
        u"[s\u00f9dwest-afrika (angola)]": "angola",
        u"republic of cyprus": "cyprus",
        u"costa rica/honduras": "costa rica",
        u"honduras or belize": "belize",
        u"dominican republican": "dominican republic",
        u"[iran]": "iran",
        u"german east africa [tanzania]": "tanzania",
        u"british honduras": "honduras",
        u"isreal/jordan": "jordan",
        u"indo china": "china",
        u"republic of honduras": "honduras",
        u"ethiopia, captive": "ethiopia",
        u"germaniae [germany; now poland]": "germany",
        u"the bahamas": "bahamas",
        u"canada, united states": "united states",
        u"south georgia and the south sandwich islands": "south georgia and the south sandwich islands",
        u"brazil, guyana, french guiana, surinam": "french guiana",
        u"virgin islands, british (uk)": "virgin islands, british",
        u"republic of singapore": "singapore",
        u"west germany": "germany",
        u"[martinique]": "martinique",
        u"[antarctica]": "antarctica",
        u"brazil-guyana boundary": "brazil",
        u"asia bor orientalis (russian federation)": "russian federation",
        u"west greenland": "greenland",
        u"gold coast, ghana": "ghana",
        u"costa rica/panama/honduras": "panama",
        u"congo, republic of the": "congo, the democratic republic of the",
        u"kingdom of saudi arabia": "saudi arabia",
        u"slovenia (yugoslavia)": "slovenia",
        u"porto rico [puerto rico]": "puerto rico",
        u"[singapore]": "singapore",
        u"france [italy]": "france",
        u"[french polynesia]": "french polynesia",
        u"kingdom of morocco": "morocco",
        u"norvegia [norway]": "norway",
        u"south russia [=ukraine]": "ukraine",
        u"rwanda/burundi": "burundi",
        u"s cook islands": "cook islands",
        u"panama/costa rica": "panama",
        u"belarus  (belorussia)": "belarus",
        u"democratic republic of congo/tanzania": "congo, the democratic republic of the",
        u"palau islands": "palau",
        u"france or germany": "france",
        u"democratic republic of congo": "congo, the democratic republic of the",
        u"leeward islands: montserrat": "montserrat",
        u"democratic republic of timor-leste": "timor-leste",
        u"panama/brazil": "brazil",
        u"zaire - enter as congo, democratic republic of": "congo, the democratic republic of the",
        u"siam (=thailand)": "thailand",
        u"argentina & bolivia": "argentina",
        u"pitcairn islands": "pitcairn",
        u"turkistan [=kyrgyzstan]": "kyrgyzstan",
        u"brazil/chile": "brazil",
        u"jamaica.": "jamaica",
        u"saudi arabia/united arab emirates": "united arab emirates",
        u"pitcairn isl": "pitcairn",
        u"germany ()": "germany",
        u"istria [croatia]": "croatia",
        u"united kingdom of great britain": "united kingdom",
        u"germany [france]": "france",
        u"ferghana [= kyrgyzstan]": "kyrgyzstan",
        u"mexico city": "mexico",
        u"brasilien [brazil]": "brazil",
        u"[malaysia]": "malaysia",
        u"republic of congo": "congo, the democratic republic of the",
        u"palestine/jordan": "jordan",
        u"island of guam": "guam",
        u"china, people's republic": "china",
        u"germany (east)": "germany",
        u"france & netherlands": "netherlands",
        u"panama/guatemala": "guatemala",
        u"gambia, the": "gambia",
        u"tanzania, captive": "tanzania",
        u"mexico/panama": "panama",
        u"usa-barbados": "barbados",
        u"malawi, mozambique, tanzania": "mozambique",
        u"honduras/nicaragua": "nicaragua",
        u"bahamas.": "bahamas",
        u"algeria/morocco": "algeria",
        u"panama city": "panama",
        u"republica dominicana [dominican republic]": "dominican republic",
        u"[peru]": "peru",
        u"indonesia, malaysia": "malaysia",
        u"\"germany'": "germany",
        u"\"germany\"": "germany",
        u"deutsch-ostafrika [east africa, tanzania]": "tanzania",
        u"south of japan": "japan",
        u"puerto rico (usa)": "puerto rico",
        u"netherlands, kingdom of the": "netherlands",
        u"republic of bulgaria": "bulgaria",
        u"pakistan and baluchistan": "pakistan",
        u"south georgia and south sandwich islands": "south georgia and the south sandwich islands",
        u"\"italy\"": "italy",
        u"united republic of tanzania": "tanzania",
        u"republic of chile": "chile",
        u"ukrainian ssr [=ukraine]": "ukraine",
        u"[kenya]": "kenya",
        u"soloman is.": "oman",
        u"montevideo, uruguay": "uruguay",
        u"s. cook islands": "cook islands",
        u"argentina/chile": "argentina",
        u"cuba ()": "cuba",
        u"gambia.": "gambia",
        u"france/italy/slovenia/spain": "france",
        u"dominican republic/haiti": "haiti",
        u"germany, west": "germany",
        u"latvia (lettland)": "latvia",
        u"belize (british honduras)": "belize",
        u"lower canada": "canada",
        u"bolivia/paraguay/uruguay/venezuela": "venezuela",
        u"trinidad/venezuela": "venezuela",
        u"\u00bf probably from lebanon or syria \u00bf": "lebanon",
        u"congo [central africa, zaire]": "congo, the democratic republic of the",
        u"cabo verde islands": "cabo verde",
        u"kingdom of sweden": "sweden",
        u"kingdom of spain": "spain",
        u"chile/argentina": "argentina",
        u"british east africa [kenya]": "kenya",
        u"australia/papua new guinea": "papua new guinea",
        u"papua-new guinea": "papua new guinea",
        u"independent state of papua new guinea": "papua new guinea",
        u"papua (the british new guinea)": "papua new guinea",
        u"papua (british new guinea)": "papua new guinea",
        u"papua new guinea/solomon islands": "papua new guinea",
        u"new guinea / papua new guinea": "papua new guinea",
        u"papua new guinea": "papua new guinea",
        u"british new guinea [papua new guinea]": "papua new guinea",
        u"australia/indonesia/papua new guinea": "papua new guinea",
        u"papaua new guinea": "papua new guinea",
        u"papau new guinea": "papua new guinea",
        u"papa new guinea": "papua new guinea",
        u"anglo-egyptian sudan": "sudan",
        u"united states minor outlying islands": "united states minor outlying islands",
        u"somaliland": "somalia",
        u"western samoa": "samoa",
        u"[camaroon]": "cameroon",
        u"central african empire": "central african republic",
        u"central african rep": "central african republic",
        u"erithrea": "eritrea",
        u"ethiopis (british east africa)": "ethiopia",
        u"gaboon": "gabon",
        u"gabooon": "gabon",
        u"guinée": "guinea",
        u"madgascar": "madagascar",
        u"madeira": "portugal",
        u"namaibia": "namibia",
        u"nambia": "namibia",
        u"nambia (southwest africa)": "namibia",
        u"republic of cape verde": "cabo verde",
        u"rhodesia": "zimbabwe",
        u"sao tome and principe": "sao tome and principe",
        u"sao tomé and príncipe": "sao tome and principe",
        u"são tomé and príncipe": "sao tome and principe",
        u"sao tome & principe": "sao tome and principe",
        u"são tomé & príncipe": "sao tome and principe",
        u"soalia": "somalia",
        u"somaliland": "somalia",
        u"somililand": "somalia",
        u"spanish overseas territory": "spain",
        u"south rhodesia": "zimbabwe",
        u"syria.": "syria",
        u"taganyika": "tanzania",
        u"tangananyika": "tanzania",
        u"tanganyika": "tanzania",
        u"(tanganyika)": "tanzania",
        u"tanganyikat": "tanzania",
        u"tanganyika terr.": "tanzania",
        u"tansania": "tanzania",
        u"transvaal province": "south africa",
        u"zaire()": "congo, the democratic republic of the",
        u"zaire].": "congo, the democratic republic of the",
        u"zanzibar": "tanzania",
        u"cameroun": "cameroon",
        u"cape verde": "cabo verde",
        u"(cf) zaire": "congo, the democratic republic of the",
        u"german east africa": "tanzania",
        u"german east africa [=tanganyika territory]": "tanzania",
        u"u.s. virgin islands": "virgin islands, u.s.",
        u"virgin islands of the united states": "virgin islands, u.s.",
        u"virgin islands (united states of america)": "virgin islands, u.s.",
        u"virgin islands, us": "virgin islands, u.s.",
        u"virgin islands (u.k.)": "virgin islands, british",
        u"[american samoa]": "american samoa",
        u"american somoa/w. somoa": "american samoa",
        u"united republic of tanganyika and zanzibar": "tanzania",
        u"philiippines": "philippines",
        u"philipine islands": "philippines",
        u"philipines": "philippines",
        u"philipines.": "philippines",
        u"philipinnes": "philippines",
        u"philippine id.": "philippines",
        u"philippine ids": "philippines",
        u"philippine is": "philippines",
        u"philippine is.": "philippines",
        u"philippine island": "philippines",
        u"philippine island/s": "philippines",
        u"philippine": "philippines",
        u"philippine. islands": "philippines",
        u"philipplines": "philippines",
        u"phillipine ids.": "philippines",
        u"phillipine islands": "philippines",
        u"phillipines id.": "philippines",
        u"phillipines": "philippines",
        u"phillippine islands": "philippines",
        u"phillippines": "philippines",
        u"philppines": "philippines",
        u"phippines": "philippines",
        u"phlippines": "philippines",
        u"pierto rico": "puerto rico",
        u"porto rico": "puerto rico",
        u"poto rico": "puerto rico",
        u"puert rico": "puerto rico",
        u"puerto rica": "puerto rico",
        u"puertorico": "puerto rico",
        u"caanda": "canada",
        u"canaada": "canada",
        u"cananda": "canada",
        u"canda": "canada",
        u"candada": "canada",
        u"viet nam": "vietnam",
        u"vatican city": "holy see (vatican city state)",
        u"england": "united kingdom",
        u"laos": "lao people's democratic republic"
    },

    "stateprovince": {
        u"(virginia )": "virginia",
        u"(wy)": "wyoming",
        u"[alaska]": "alaska",
        u"[california]": "california",
        u"[idaho or washington]": "idaho",
        u"[illinois]": "illinois",
        u"[indiana]": "indiana",
        u"[louisiana]": "louisiana",
        u"[ma]": "massachusetts",
        u"[me]": "maine",
        u"[mt]": "montana",
        u"[nd]": "north dakota",
        u"[nebraska]": "nebraska",
        u"[north carolina]": "north carolina",
        u"[oregon]": "oregon",
        u"[pa]": "pennsylvania",
        u"[south] dakota": "south dakota",
        u"[tennessee/ virginia]": "tennessee",
        u"[tennessee]": "tennessee",
        u"[tx]": "texas",
        u"[wa]": "washington",
        u"[wy]": "wyoming",
        u"\"virginia,\"": "virginia",
        u"\"wisconsin,\"": "wisconsin",
        u"ak": "alaska",
        u"al": "alabama",
        u"alabama & mississippi": "alabama",
        u"alabama, florida": "alabama",
        u"alabama, mississippi": "alabama",
        u"alabama, tennessee": "alabama",
        u"alabama-mississippi state line": "alabama",
        u"alabama/arkansas": "alabama",
        u"alabama/florida": "alabama",
        u"alabama/florida/georgia/louisiana": "alabama",
        u"alabama/florida/georgia/pennsylvania/tennessee/virginia": "alabama",
        u"alabama/florida/georgia/texas/virginia": "alabama",
        u"alabama/georgia": "alabama",
        u"alabama/georgia/louisiana/mississippi": "alabama",
        u"alabama/georgia/mississippi/north carolina/tennessee/virginia": "alabama",
        u"alabama/georgia/north carolina/south carolina": "alabama",
        u"alabama/tennessee": "alabama",
        u"alaksa": "alaska",
        u"alamaba": "alabama",
        u"alambama": "alabama",
        u"alasa": "alaska",
        u"alasaka": "alaska",
        u"alaska, yukon": "alaska",
        u"alaska/oregon/washington": "alaska",
        u"alaskaa": "alaska",
        u"albama": "alabama",
        u"aleutian islands": "alaska",
        u"ar": "arkansas",
        u"ariona": "arizona",
        u"ariozona": "arizona",
        u"arizon": "arizona",
        u"arizona & california": "arizona",
        u"arizona or utah": "arizona",
        u"arizona, new mexico": "arizona",
        u"arizona, utah": "arizona",
        u"arizona/california": "arizona",
        u"arizona/colorado/montana/nevada/wyoming": "arizona",
        u"arizona/new mexico": "arizona",
        u"arizona/new mexico/texas": "arizona",
        u"arizona/new mexico/utah": "arizona",
        u"arizona/utah": "arizona",
        u"arkansa": "arkansas",
        u"arkansas, mississippi": "arkansas",
        u"arkansas, oklahoma": "arkansas",
        u"arkansas/illinois/iowa/kansas/nebraska": "arkansas",
        u"arkansas/indiana/michigan/missouri": "arkansas",
        u"arkansas/texas/new mexico": "arkansas",
        u"arziona": "arizona",
        u"arzona": "arizona",
        u"az": "arizona",
        u"bergen co., new jersey": "new jersey",
        u"ca [=az]": "arizona",
        u"ca": "california",
        u"cal": "california",
        u"calafornia": "california",
        u"calfornia": "california",
        u"califo": "california",
        u"califonia": "california",
        u"califonria": "california",
        u"califonrnia": "california",
        u"califorani": "california",
        u"califoria": "california",
        u"califorina": "california",
        u"califorinia": "california",
        u"californa": "california",
        u"californai": "california",
        u"california and washington": "california",
        u"california or nevada": "california",
        u"california": "california",
        u"california, nevada": "california",
        u"california, oregon": "california",
        u"california/colorado/idaho/new mexico/ utah/washington/saskatchewan": "california",
        u"california/colorado/oregon/washington/wyoming/british columbia": "california",
        u"california/florida": "california",
        u"california/oregon": "california",
        u"califronia": "california",
        u"calilf": "california",
        u"calilfornia": "california",
        u"calilifornia": "california",
        u"caliornia": "california",
        u"callifornia": "california",
        u"cnnecticut": "connecticut",
        u"co []": "colorado",
        u"co": "colorado",
        u"col": "colorado",
        u"colarado": "colorado",
        u"colorad": "colorado",
        u"colorad0": "colorado",
        u"coloradao": "colorado",
        u"colorade": "colorado",
        u"colorado - new mexico - oklahoma": "colorado",
        u"colorado, kansas": "colorado",
        u"colorado, utah": "colorado",
        u"colorado/mississippi/missouri/texas": "colorado",
        u"colorado/montana/north dakota": "colorado",
        u"colorado/texas": "colorado",
        u"colorado/wyoming/montana": "colorado",
        u"coloradoo": "colorado",
        u"colroado": "colorado",
        u"conn": "connecticut",
        u"connecticut, massaschusetts": "connecticut",
        u"connecticut, new jersey": "connecticut",
        u"connecticut/florida": "connecticut",
        u"connecticut/maine/massachusetts/new hampshire/vermont": "connecticut",
        u"connecticut/maine/new hampshire/vermont": "connecticut",
        u"connecticut/maryland/new hampshire/new jersey/new york/virginia/wash dc": "connecticut",
        u"connecticut/maryland/new jersey/new york/pennsylania": "connecticut",
        u"connecticut/massachusetts/new york/pennsylvania": "connecticut",
        u"connecticut/new jersey/new york": "connecticut",
        u"connecticut/ohio/massachusetts": "connecticut",
        u"connecticut/pennsylvania/new york/rhode island pennsylvania": "connecticut",
        u"connecticutt": "connecticut",
        u"conneticut": "connecticut",
        u"coorado": "colorado",
        u"ct": "connecticut",
        u"d.c.": "washington, d.c.",
        u"dc": "washington, d.c.",
        u"delaware/maryland": "delaware",
        u"delaware/maryland/new jersey/new york": "delaware",
        u"deleware": "delaware",
        u"delware": "delaware",
        u"dist. of columbia": "washington, d.c.",
        u"district of colombia": "washington, d.c.",
        u"district of colubia": "washington, d.c.",
        u"district of columbia": "washington, d.c.",
        u"distrit of columbia": "washington, d.c.",
        u"douth dakota": "south dakota",
        u"eastern north carolina": "north carolina",
        u"fl ()": "florida",
        u"fl": "florida",
        u"floida": "florida",
        u"flor": "florida",
        u"florida or georgia": "florida",
        u"florida": "florida",
        u"florida-georgia": "florida",
        u"florida/georgia border": "florida",
        u"florida/georgia": "florida",
        u"florida/georgia/louisiana/mississippi": "florida",
        u"florida/louisiana/north carolina": "florida",
        u"florida/mississippi": "florida",
        u"florida/mississippi/alabama": "florida",
        u"florida/pennsylvania": "florida",
        u"florida/south carolina": "florida",
        u"florida/tennessee": "florida",
        u"floriida": "florida",
        u"florioda": "florida",
        u"floroda": "florida",
        u"ga": "georgia",
        u"geogia": "georgia",
        u"geor": "georgia",
        u"georgia or florida": "georgia",
        u"georgia/ south carolina": "georgia",
        u"georgia/alabama": "georgia",
        u"georgia/louisiana": "georgia",
        u"georgia/mississippi": "georgia",
        u"georgia/tennessee/west virginia": "georgia",
        u"georgia/texas": "georgia",
        u"gerogia": "georgia",
        u"gerorgia": "georgia",
        u"ha": "hawaii",
        u"haw": "hawaii",
        u"haw. ids.": "hawaii",
        u"hawaii": "hawaii",
        u"hawaii, oahu island": "hawaii",
        u"hawaii0003268": "hawaii",
        u"hawaiian islands": "hawaii",
        u"hawaiian": "hawaii",
        u"hi": "hawaii",
        u"ia": "iowa",
        u"id": "idaho",
        u"ida": "idaho",
        u"idado": "idaho",
        u"idaho, montana": "idaho",
        u"idaho, washington": "idaho",
        u"idaho,/illinois/indiana/iowa/michigan/utah": "idaho",
        u"idaho/oregon/washington": "idaho",
        u"idaho/washington/british columbia": "idaho",
        u"idaho/washington/vancouver": "idaho",
        u"iillinois": "illinois",
        u"il": "illinois",
        u"ilinois": "illinois",
        u"illiinois": "illinois",
        u"illiniois": "illinois",
        u"illinios": "illinois",
        u"illinois": "illinois",
        u"illinois, new york": "illinois",
        u"illinois-indiana": "illinois",
        u"illinois/indiana/minnesota/wisconsin": "illinois",
        u"illinois/indiana/missouri/ohio": "illinois",
        u"illinois/iowa/michigan": "illinois",
        u"illinois/michigan/wisconsin": "illinois",
        u"illinois`": "illinois",
        u"illinoise": "illinois",
        u"illlinois": "illinois",
        u"illnois": "illinois",
        u"in": "indiana",
        u"indiana/iowa/minnesota/ohio/wisconsin": "indiana",
        u"indiana/kentucky": "indiana",
        u"indiana/kentucky/maryland/ohio/washington d.c./west virginia": "indiana",
        u"iowa co.": "iowa",
        u"iowa/kansas/minnesota/oklahoma/missouri": "iowa",
        u"iowa/kansas/oklahoma": "iowa",
        u"iowa/michigan/missouri/ohio/wisconsin/ontario": "iowa",
        u"iowa/missouri/nebraska/ohio/pennsylvania/south dakota/west virginia": "iowa",
        u"iowas": "iowa",
        u"kansas/missouri": "kansas",
        u"kansas/texas": "kansas",
        u"kansasashington": "kansas",
        u"kentuck": "kentucky",
        u"kentucky or tennessee": "kentucky",
        u"kentucky/indiana": "kentucky",
        u"kentucky/maryland/north carolina/tennessee/virginia/west virginia": "kentucky",
        u"kentucky/maryland/virginia/west virginia": "kentucky",
        u"kentucky/new york": "kentucky",
        u"kentucky/north carolina/tennessee/virginia/west virginia": "kentucky",
        u"kentuncky": "kentucky",
        u"keutucky": "kentucky",
        u"la": "louisiana",
        u"lllinois": "illinois",
        u"louisana": "louisiana",
        u"louisiana*": "louisiana",
        u"louisiana, mississippi": "louisiana",
        u"louisiana/miss.": "louisiana",
        u"louisiana/mississippi": "louisiana",
        u"louisianna": "louisiana",
        u"lousiana & alabama": "louisiana",
        u"lousiana": "louisiana",
        u"lousisiana": "louisiana",
        u"ma ()": "massachusetts",
        u"ma": "massachusetts",
        u"ma, me, vt, ri, cn": "massachusetts",
        u"main": "maine",
        u"maine/massachusetts/michigan/wisconisn/ottawa": "maine",
        u"maine/massachusetts/new hampshire/vermont": "maine",
        u"maine/massachusetts/vermont": "maine",
        u"maine/new brunswick": "maine",
        u"maine/new hampshire/vermont": "maine",
        u"maine/vermont": "maine",
        u"maine/vermont/new hampshire/rhode island/connecticut": "maine",
        u"marland": "maryland",
        u"marlyland": "maryland",
        u"maryland, new jersey": "maryland",
        u"maryland/virginia": "maryland",
        u"maryland/virginia/washington d.c.": "maryland",
        u"maryland/virginia/west virginia": "maryland",
        u"masachusetts": "massachusetts",
        u"mass": "massachusetts",
        u"massacheusetts": "massachusetts",
        u"massachuetts": "massachusetts",
        u"massachusets": "massachusetts",
        u"massachusettes": "massachusetts",
        u"massachusetts": "massachusetts",
        u"massachusetts/ connecticut": "massachusetts",
        u"massachusetts/maine": "massachusetts",
        u"massachusetts/michigan/new hampshire/wisconsin": "massachusetts",
        u"massachusetts/new hampshire": "massachusetts",
        u"massachusetts/rhode island": "massachusetts",
        u"massachussets": "massachusetts",
        u"massachussettes": "massachusetts",
        u"massachussetts": "massachusetts",
        u"massachusstts": "massachusetts",
        u"masschusetts": "massachusetts",
        u"masssachusetts": "massachusetts",
        u"md": "maryland",
        u"me": "maine",
        u"me. or ma.": "maine",
        u"mi": "michigan",
        u"mich": "michigan",
        u"michgan": "michigan",
        u"michigan": "michigan",
        u"michigan, ohio": "michigan",
        u"michigan, ontario": "michigan",
        u"michigan, wisconsin": "michigan",
        u"michigan/minnesota/iowa/kansas/texas/wisconsin": "michigan",
        u"michigan/tennessee": "michigan",
        u"michigan/wisconsin/illinois/indiana": "michigan",
        u"michigan/wisconsin/minnesota": "michigan",
        u"mighican": "michigan",
        u"mighigan": "michigan",
        u"minneosta": "minnesota",
        u"minnesota, new york": "minnesota",
        u"minnesota/ iowa": "minnesota",
        u"minnesota/wisconsin": "minnesota",
        u"minnesotra": "minnesota",
        u"minnestoa": "minnesota",
        u"minnestota": "minnesota",
        u"misouri": "missouri",
        u"mississipi": "mississippi",
        u"mississippi [=louisiana]": "louisiana",
        u"mississippi/louisiana/texas/arizona": "mississippi",
        u"mississipppi": "mississippi",
        u"mississppi": "mississippi",
        u"misso": "missouri",
        u"missorui": "missouri",
        u"missouri or arkansas": "missouri",
        u"mn ()": "montana",
        u"mn": "minnesota",
        u"mon tana": "montana",
        u"monatana": "montana",
        u"montana": "montana",
        u"montana, north dakota": "montana",
        u"montana, wyoming": "montana",
        u"montana/nebraska/south dakota": "montana",
        u"montana/south dakota/wyoming": "montana",
        u"montana/wyoming": "montana",
        u"montanta": "montana",
        u"ms": "mississippi",
        u"nc": "north carolina",
        u"nc/tn": "north carolina",
        u"nd": "north dakota",
        u"ne/ca": "nebraska",
        u"nebaska": "nebraska",
        u"nebraska or dakota": "nebraska",
        u"nebraska/wyoming": "nebraska",
        u"neew york": "new york",
        u"nevada/arizona": "nevada",
        u"new  york": "new york",
        u"new hamphire": "new hampshire",
        u"new hampshie": "new hampshire",
        u"new hampshire or new york": "new hampshire",
        u"new hampshire/maine": "new hampshire",
        u"new hampshire/wisconsin/idaho": "new hampshire",
        u"new hampshirt": "new hampshire",
        u"new hampshre": "new hampshire",
        u"new hampsire": "new hampshire",
        u"new hamshire": "new hampshire",
        u"new hamsphire": "new hampshire",
        u"new jersery": "new jersey",
        u"new jersey and new york": "new jersey",
        u"new jersey and ohio": "new jersey",
        u"new jersey and pennsylvania": "new jersey",
        u"new jersey to florida": "new jersey",
        u"new jersey, new york": "new jersey",
        u"new jersey, new york, colorado": "new jersey",
        u"new jersey/delaware": "new jersey",
        u"new jersey/new york": "new jersey",
        u"new meico": "new mexico",
        u"new mexico and texas": "new mexico",
        u"new mexico/california": "new mexico",
        u"new mexico/colorado": "new mexico",
        u"new mexico/texas": "new mexico",
        u"new york & vermont": "new york",
        u"new york or penna": "new york",
        u"new york, pennsylvania": "new york",
        u"new york/florida": "new york",
        u"new york/louisiana": "new york",
        u"new york/massachusetts": "new york",
        u"new york/new jersey": "new york",
        u"new york/pennsylvania": "new york",
        u"new york/vermont": "new york",
        u"new york/washington d.c.": "new york",
        u"new_mexico": "new mexico",
        u"new_york": "new york",
        u"newæhampshire": "new hampshire",
        u"newæjersey": "new jersey",
        u"newæyork": "new york",
        u"nh [=me]": "maine",
        u"nh": "new hampshire",
        u"nj": "new jersey",
        u"nm": "new mexico",
        u"north ca": "north carolina",
        u"north carlolina": "north carolina",
        u"north carolina - tennessee": "north carolina",
        u"north carolina and tennessee": "north carolina",
        u"north carolina or tennessee": "north carolina",
        u"north carolina": "north carolina",
        u"north carolina*": "north carolina",
        u"north carolina, south carolina": "north carolina",
        u"north carolina, tennessee": "north carolina",
        u"north carolina-tennessee": "north carolina",
        u"north carolina-virginia": "north carolina",
        u"north carolina/massachusetts": "north carolina",
        u"north carolina/south carolina/tennessee": "north carolina",
        u"north carolina/tennessee": "north carolina",
        u"north caroline": "north carolina",
        u"north caronlina": "north carolina",
        u"north dakota, south dakota": "north dakota",
        u"north dakota, wyoming": "north dakota",
        u"northæcarolina": "north carolina",
        u"noth carolina": "north carolina",
        u"nv": "nevada",
        u"ny": "new york",
        u"off virginia": "virginia",
        u"oh": "ohio",
        u"ohiio": "ohio",
        u"ohio*": "ohio",
        u"ohio/maryland/massachusetts/rhode island": "ohio",
        u"ohio/massachusetts": "ohio",
        u"ohio/pennsylvania": "ohio",
        u"ohio/tennessee": "ohio",
        u"ohio/west virginia": "ohio",
        u"ok": "oklahoma",
        u"ok, ut, tx": "oklahoma",
        u"oklaahoma": "oklahoma",
        u"oklaholma": "oklahoma",
        u"oklahom": "oklahoma",
        u"oklahoma-texas": "oklahoma",
        u"oklahoma/nebraska/arkansas/texas": "oklahoma",
        u"oklahoma/texas": "oklahoma",
        u"or": "oregon",
        u"oregan": "oregon",
        u"oregeon": "oregon",
        u"oregon, washington": "oregon",
        u"oregon, washinton": "oregon",
        u"oregon/california": "oregon",
        u"oregon/washington/alaska": "oregon",
        u"oregon/washington/wyoming/utah/texas": "oregon",
        u"organ": "oregon",
        u"orgegon": "oregon",
        u"pa": "pennsylvania",
        u"pennsilvania": "pennsylvania",
        u"pennslyvania": "pennsylvania",
        u"pennsylania": "pennsylvania",
        u"pennsylvaina": "pennsylvania",
        u"pennsylvania and ohio": "pennsylvania",
        u"pennsylvania/kentucky": "pennsylvania",
        u"pennsylvanis": "pennsylvania",
        u"pennsylvannia": "pennsylvania",
        u"pennsynvania": "pennsylvania",
        u"pennyslvania": "pennsylvania",
        u"penssylvania": "pennsylvania",
        u"philadelphia": "pennsylvania",
        # u"puerto rico": "puerto rico",
        u"rhode island": "rhode island",
        u"ri": "rhode island",
        u"s. w. virginia": "virginia",
        u"sacramento": "california",
        u"sc": "south carolina",
        u"sd": "south dakota",
        u"slabama": "alabama",
        u"so dakota/nebraska": "south dakota",
        u"soiuth dakota": "south dakota",
        u"sonora, texas": "texas",
        u"sorth carolina": "south carolina",
        u"south arizona": "arizona",
        u"south carolin": "south carolina",
        u"south carolina": "south carolina",
        u"south carolina/georgia": "south carolina",
        u"south caroline": "south carolina",
        u"south dakota, wyoming": "south dakota",
        u"south dakota/wyoming": "south dakota",
        u"south datoka": "south dakota",
        u"south sakota": "south dakota",
        u"south-west virginia": "virginia",
        u"southædakota": "south dakota",
        u"teaxs": "texas",
        u"tenessee": "tennessee",
        u"tennesee": "tennessee",
        u"tennesse": "tennessee",
        u"tennesse/north carolina": "tennessee",
        u"tennessee /north carolina": "tennessee",
        u"tennessee and north carolina": "tennessee",
        u"tennessee": "tennessee",
        u"tennessee-north carolina state line": "tennessee",
        u"tennessee-north carolina": "tennessee",
        u"tennessee/kentucky": "tennessee",
        u"tennessee/north carolina": "tennessee",
        u"tennessee/oregon": "tennessee",
        u"tennesseee": "tennessee",
        u"tennesssee": "tennessee",
        u"texa": "texas",
        u"texas": "texas",
        u"texas/arkansas": "texas",
        u"texas/florida": "texas",
        u"texas/louisiana": "texas",
        u"texas/louisiana/mississippi": "texas",
        u"texas/oklahoma": "texas",
        u"texas/oklahoma/kansas": "texas",
        u"texas/pennsylvania": "texas",
        u"texs": "texas",
        u"tn": "tennessee",
        u"tn-n.c.": "tennessee",
        u"tx": "texas",
        u"uniontown, d.c.": "washington, d.c.",
        u"uta": "utah",
        u"utah/new mexico": "utah",
        u"utha": "utah",
        u"va [=md]": "maryland",
        u"va": "virginia",
        u"vemont": "vermont",
        u"ver": "vermont",
        u"vermong": "vermont",
        u"vermont ()": "vermont",
        u"vermont/new hampshire": "vermont",
        u"vermont/new york": "vermont",
        u"vermont/new york/quebec": "vermont",
        u"viginia": "virginia",
        u"virgina": "virginia",
        u"virginia, west virginia": "virginia",
        u"virginia/tennessee": "virginia",
        u"viriginia": "virginia",
        u"vt": "vermont",
        u"vt-nh": "vermont",
        u"vt/nh": "vermont",
        u"w. t. [=wa]": "washington",
        u"w.t. [=wa]": "washington",
        u"wa": "washington",
        u"wash": "washington",
        u"washing": "washington",
        u"washingon": "washington",
        u"washingotn territory [=wa]": "washington",
        u"washingotn": "washington",
        u"washingrton": "washington",
        u"washington (state)": "washington",
        u"washington d. c.": "washington, d.c.",
        u"washington d.c.": "washington, d.c.",
        u"washington d.c., florida": "washington, d.c.",
        u"washington dc": "washington, d.c.",
        u"washington state": "washington",
        u"washington territory": "washington",
        u"washington, d. c.": "washington, d.c.",
        u"washington, d.c.": "washington, d.c.",
        u"washington, district of columbia": "washington, d.c.",
        u"washington.": "washington",
        u"washington/vancouver": "washington",
        u"washinton": "washington",
        u"washngton": "washington",
        u"wasington": "washington",
        u"west virgiana": "west virginia",
        u"west virgina": "west virginia",
        u"west virginia- ohio": "west virginia",
        u"west viriginia": "west virginia",
        u"western north carolina": "north carolina",
        u"westævirginia": "west virginia",
        u"wi, mi or mn": "wisconsin",
        u"wiconsin": "wisconsin",
        u"wilsconsin": "wisconsin",
        u"winconsin": "wisconsin",
        u"wisc": "wisconsin",
        u"wisconsin, other": "wisconsin",
        u"wisconsin/illinois": "wisconsin",
        u"wisconsin/michigan": "wisconsin",
        u"wisconsin/minnesota": "wisconsin",
        u"wiscosin": "wisconsin",
        u"wisonsin": "wisconsin",
        u"wisonsion": "wisconsin",
        u"wv": "west virginia",
        u"wy": "wyoming",
        u"wy,grand teton national park": "wyoming",
        u"wyomin": "wyoming",
        u"wyoming (most likely)": "wyoming",
        u"wyoming/colorado": "wyoming",
        u"wyoming/south dakota": "wyoming",
        u"wyoming/texas/new mexico/utah/arizona/arkansas/california": "wyoming",
        u"wyomiong": "wyoming",
        u"wyomning": "wyoming",
    }
}

kl["country"].update(kl_none)
kl["continent"].update(kl_none)
kl["stateprovince"].update(kl_none)

real_continents = {
    "europe",
    "asia",
    "australia",
    "africa",
    "north america",
    "south america",
    "antarctica",
    "oceania"
}

major_bodies_of_water = {
    "atlantic",
    "arctic",
    "antarctic",
    "pacific",
    "indian",
    "caribbean",
    "mediterranean",
    "bering"
}

major_bodies_of_water_type = {
    "atlantic": "ocean",
    "arctic": "ocean",
    "antarctic": "ocean",
    "pacific": "ocean",
    "indian": "ocean",
    "caribbean": "sea",
    "mediterranean": "sea",
    "bering": "sea",
}

mbw_complete = set([k + " " + major_bodies_of_water_type[k] for k in major_bodies_of_water])

real_continents |= mbw_complete | major_bodies_of_water

string_to_iso_code = {
    u"aruba": "abw",
    u"afghanistan": "afg",
    u"angola": "ago",
    u"anguilla": "aia",
    u"åland islands": "ala",
    u"albania": "alb",
    u"andorra": "and",
    u"united arab emirates": "are",
    u"argentina": "arg",
    u"armenia": "arm",
    u"american samoa": "asm",
    u"antarctica": "ata",
    u"french southern territories": "atf",
    u"antigua and barbuda": "atg",
    u"australia": "aus",
    u"austria": "aut",
    u"azerbaijan": "aze",
    u"burundi": "bdi",
    u"belgium": "bel",
    u"benin": "ben",
    u"bonaire, sint eustatius and saba": "bes",
    u"burkina faso": "bfa",
    u"bangladesh": "bgd",
    u"bulgaria": "bgr",
    u"bahrain": "bhr",
    u"bahamas": "bhs",
    u"bosnia and herzegovina": "bih",
    u"saint barthélemy": "blm",
    u"belarus": "blr",
    u"belize": "blz",
    u"bermuda": "bmu",
    u"bolivia": "bol",
    u"brazil": "bra",
    u"barbados": "brb",
    u"brunei darussalam": "brn",
    u"bhutan": "btn",
    u"bouvet island": "bvt",
    u"botswana": "bwa",
    u"central african republic": "caf",
    u"canada": "can",
    u"cocos (keeling) islands": "cck",
    u"switzerland": "che",
    u"chile": "chl",
    u"china": "chn",
    u"côte d'ivoire": "civ",
    u"cameroon": "cmr",
    u"congo, the democratic republic of the": "cod",
    u"cook islands": "cok",
    u"colombia": "col",
    u"comoros": "com",
    u"cabo verde": "cpv",
    u"costa rica": "cri",
    u"cuba": "cub",
    u"curaçao": "cuw",
    u"christmas island": "cxr",
    u"cayman islands": "cym",
    u"cyprus": "cyp",
    u"czech republic": "cze",
    u"germany": "deu",
    u"djibouti": "dji",
    u"dominica": "dma",
    u"denmark": "dnk",
    u"dominican republic": "dom",
    u"algeria": "dza",
    u"ecuador": "ecu",
    u"egypt": "egy",
    u"eritrea": "eri",
    u"western sahara": "esh",
    u"spain": "esp",
    u"estonia": "est",
    u"ethiopia": "eth",
    u"finland": "fin",
    u"fiji": "fji",
    u"falkland islands": "flk",
    u"france": "fra",
    u"faroe islands": "fro",
    u"federated states of micronesia": "fsm",
    u"gabon": "gab",
    u"united kingdom": "gbr",
    u"georgia": "geo",
    u"guernsey": "ggy",
    u"ghana": "gha",
    u"gibraltar": "gib",
    u"guadeloupe": "glp",
    u"gambia": "gmb",
    u"guinea-bissau": "gnb",
    u"equatorial guinea": "gnq",
    u"greece": "grc",
    u"grenada": "grd",
    u"greenland": "grl",
    u"guatemala": "gtm",
    u"french guiana": "guf",
    u"guam": "gum",
    u"guyana": "guy",
    u"hong kong": "hkg",
    u"heard island and mcdonald islands": "hmd",
    u"honduras": "hnd",
    u"croatia": "hrv",
    u"haiti": "hti",
    u"hungary": "hun",
    u"indonesia": "idn",
    u"isle of man": "imn",
    u"india": "ind",
    u"british indian ocean territory": "iot",
    u"ireland": "irl",
    u"iran": "irn",
    u"iraq": "irq",
    u"iceland": "isl",
    u"israel": "isr",
    u"italy": "ita",
    u"jamaica": "jam",
    u"jersey": "jey",
    u"jordan": "jor",
    u"japan": "jpn",
    u"kazakhstan": "kaz",
    u"kenya": "ken",
    u"kyrgyzstan": "kgz",
    u"cambodia": "khm",
    u"kiribati": "kir",
    u"saint kitts and nevis": "kna",
    u"south korea": "kor",
    u"kuwait": "kwt",
    u"lao people's democratic republic": "lao",
    u"lebanon": "lbn",
    u"liberia": "lbr",
    u"libya": "lby",
    u"saint lucia": "lca",
    u"liechtenstein": "lie",
    u"sri lanka": "lka",
    u"lesotho": "lso",
    u"lithuania": "ltu",
    u"luxembourg": "lux",
    u"latvia": "lva",
    u"macao": "mac",
    u"saint martin (french part)": "maf",
    u"morocco": "mar",
    u"monaco": "mco",
    u"moldova, republic of": "mda",
    u"madagascar": "mdg",
    u"maldives": "mdv",
    u"mexico": "mex",
    u"marshall islands": "mhl",
    u"macedonia": "mkd",
    u"malta": "mlt",
    u"myanmar": "mmr",
    u"montenegro": "mne",
    u"mongolia": "mng",
    u"northern mariana islands": "mnp",
    u"mozambique": "moz",
    u"mauritania": "mrt",
    u"montserrat": "msr",
    u"martinique": "mtq",
    u"mauritius": "mus",
    u"malawi": "mwi",
    u"malaysia": "mys",
    u"mayotte": "myt",
    u"namibia": "nam",
    u"new caledonia": "ncl",
    u"niger": "ner",
    u"norfolk island": "nfk",
    u"nigeria": "nga",
    u"nicaragua": "nic",
    u"niue": "niu",
    u"netherlands": "nld",
    u"norway": "nor",
    u"nepal": "npl",
    u"nauru": "nru",
    u"new zealand": "nzl",
    u"pakistan": "pak",
    u"panama": "pan",
    u"pitcairn": "pcn",
    u"peru": "per",
    u"philippines": "phl",
    u"palau": "plw",
    u"papua new guinea": "png",
    u"poland": "pol",
    u"puerto rico": "pri",
    u"north korea": "prk",
    u"portugal": "prt",
    u"paraguay": "pry",
    u"palestine, state of": "pse",
    u"french polynesia": "pyf",
    u"qatar": "qat",
    u"réunion": "reu",
    u"romania": "rou",
    u"russian federation": "rus",
    u"rwanda": "rwa",
    u"saudi arabia": "sau",
    u"sudan": "sdn",
    u"senegal": "sen",
    u"singapore": "sgp",
    u"south georgia and the south sandwich islands": "sgs",
    u"saint helena, ascension and tristan da cunha": "shn",
    u"svalbard and jan mayen": "sjm",
    u"solomon islands": "slb",
    u"sierra leone": "sle",
    u"el salvador": "slv",
    u"san marino": "smr",
    u"somalia": "som",
    u"saint pierre and miquelon": "spm",
    u"serbia": "srb",
    u"south sudan": "ssd",
    u"sao tome and principe": "stp",
    u"suriname": "sur",
    u"slovakia": "svk",
    u"slovenia": "svn",
    u"sweden": "swe",
    u"swaziland": "swz",
    u"sint maarten (dutch part)": "sxm",
    u"seychelles": "syc",
    u"syria": "syr",
    u"turks and caicos islands": "tca",
    u"chad": "tcd",
    u"togo": "tgo",
    u"thailand": "tha",
    u"tajikistan": "tjk",
    u"tokelau": "tkl",
    u"turkmenistan": "tkm",
    u"timor-leste": "tls",
    u"tonga": "ton",
    u"trinidad and tobago": "tto",
    u"tunisia": "tun",
    u"turkey": "tur",
    u"tuvalu": "tuv",
    u"taiwan": "twn",
    u"tanzania": "tza",
    u"uganda": "uga",
    u"ukraine": "ukr",
    u"united states minor outlying islands": "umi",
    u"uruguay": "ury",
    u"united states": "usa",
    u"uzbekistan": "uzb",
    u"holy see (vatican city state)": "vat",
    u"saint vincent and the grenadines": "vct",
    u"venezuela": "ven",
    u"virgin islands, british": "vgb",
    u"virgin islands, u.s.": "vir",
    u"vietnam": "vnm",
    u"vanuatu": "vut",
    u"wallis and futuna": "wlf",
    u"yemen": "yem",
    u"south africa": "zaf",
    u"zambia": "zmb",
    u"zimbabwe": "zwe",
    # Things in other things
    u"oman": "omn",
    u"samoa": "wsm",
    u"mali": "mli",
    u"guinea": "gin",
    u"congo": "cog",
}

iso_countries = set(string_to_iso_code.keys())

implied_parent = {
    "stateprovince": {
        "alabama": ["north america","united states"],
        "alaska": ["north america","united states"],
        "arizona": ["north america","united states"],
        "arkansas": ["north america","united states"],
        "california": ["north america","united states"],
        "colorado": ["north america","united states"],
        "connecticut": ["north america","united states"],
        "delaware": ["north america","united states"],
        "florida": ["north america","united states"],
        "georgia": ["north america","united states"],
        "hawaii": ["oceania", "united states"],
        "idaho": ["north america","united states"],
        "illinois": ["north america","united states"],
        "indiana": ["north america","united states"],
        "iowa": ["north america","united states"],
        "kansas": ["north america","united states"],
        "kentucky": ["north america","united states"],
        "louisiana": ["north america","united states"],
        "maine": ["north america","united states"],
        "maryland": ["north america","united states"],
        "massachusetts": ["north america","united states"],
        "michigan": ["north america","united states"],
        "minnesota": ["north america","united states"],
        "mississippi": ["north america","united states"],
        "missouri": ["north america","united states"],
        "montana": ["north america","united states"],
        "nebraska": ["north america","united states"],
        "nevada": ["north america","united states"],
        "new hampshire": ["north america","united states"],
        "new jersey": ["north america","united states"],
        "new mexico": ["north america","united states"],
        "new york": ["north america","united states"],
        "north carolina": ["north america","united states"],
        "north dakota": ["north america","united states"],
        "ohio": ["north america","united states"],
        "oklahoma": ["north america","united states"],
        "oregon": ["north america","united states"],
        "pennsylvania": ["north america","united states"],
        "rhode island": ["north america","united states"],
        "south carolina": ["north america","united states"],
        "south dakota": ["north america","united states"],
        "tennessee": ["north america","united states"],
        "texas": ["north america","united states"],
        "utah": ["north america","united states"],
        "vermont": ["north america","united states"],
        "virginia": ["north america","united states"],
        "washington": ["north america","united states"],
        "west virginia": ["north america","united states"],
        "wisconsin": ["north america","united states"],
        "wyoming": ["north america","united states"],
        "washington, d.c.": ["north america", "united states"],
    },
    "country": {
        u"afghanistan": ["asia"],
        u"albania": ["europe"],
        u"algeria": ["africa"],
        u"american samoa": ["oceania"],
        u"andorra": ["europe"],
        u"angola": ["africa"],
        u"anguilla": ["north america"],
        u"antarctica":  ["antarctica"],
        u"antigua and barbuda": ["north america"],
        u"argentina":  ["south america"],
        u"armenia": ["europe"],
        u"aruba": ["south america"],
        u"australia": ["australia"],
        u"austria": ["europe"],
        u"azerbaijan": ["europe"],
        u"bahamas": ["north america"],
        u"bahrain": ["asia"],
        u"bangladesh": ["asia"],
        u"barbados": ["north america"],
        u"belarus": ["europe"],
        u"belgium": ["europe"],
        u"belize": ["north america"],
        u"benin": ["africa"],
        u"bhutan": ["asia"],
        u"bolivia": ["south america"],
        u"bonaire, sint eustatius and saba": ["south america"],
        u"bosnia and herzegovina": ["europe"],
        u"botswana": ["africa"],
        u"brazil": ["south america"],
        u"british indian ocean territory": ["asia"],
        u"brunei darussalam": ["asia"],
        u"bulgaria": ["europe"],
        u"burkina faso": ["africa"],
        u"burundi": ["africa"],
        u"cabo verde": ["africa"],
        u"cambodia": ["asia"],
        u"cameroon": ["africa"],
        u"canada": ["north america"],
        u"cayman islands": ["north america"],
        u"central african republic": ["africa"],
        u"chad": ["africa"],
        u"chile": ["south america"],
        u"china": ["asia"],
        u"christmas island": ["asia"],
        u"cocos (keeling) islands": ["asia"],
        u"colombia": ["south america"],
        u"comoros": ["africa"],
        u"congo": ["africa"],
        u"congo, the democratic republic of the": ["africa"],
        u"cook islands": ["oceania"],
        u"costa rica": ["north america"],
        u"croatia": ["europe"],
        u"cuba": ["north america"],
        u"curaçao": ["south america"],
        u"cyprus": ["europe"],
        u"czech republic": ["europe"],
        u"côte d'ivoire": ["africa"],
        u"denmark": ["europe"],
        u"djibouti": ["africa"],
        u"dominica": ["north america"],
        u"dominican republic": ["north america"],
        u"ecuador": ["south america"],
        u"egypt": ["africa"],
        u"el salvador": ["north america"],
        u"equatorial guinea": ["africa"],
        u"eritrea": ["africa"],
        u"estonia": ["europe"],
        u"ethiopia": ["africa"],
        u"falkland islands": ["south america"],
        u"faroe islands": ["europe"],
        u"fiji": ["oceania"],
        u"finland": ["europe"],
        u"france": ["europe"],
        u"french guiana": ["south america"],
        u"french polynesia": ["oceania"],
        u"gabon": ["africa"],
        u"gambia": ["africa"],
        u"georgia": ["europe"],
        u"germany": ["europe"],
        u"ghana": ["africa"],
        u"gibraltar": ["europe"],
        u"greece": ["europe"],
        u"greenland": ["north america"],
        u"grenada": ["north america"],
        u"guadeloupe": ["north america"],
        u"guam": ["oceania"],
        u"guatemala": ["north america"],
        u"guernsey": ["europe"],
        u"guinea": ["africa"],
        u"guinea-bissau": ["africa"],
        u"guyana": ["south america"],
        u"haiti": ["north america"],
        u"holy see (vatican city state)": ["europe"],
        u"honduras": ["north america"],
        u"hong kong": ["asia"],
        u"hungary": ["europe"],
        u"iceland": ["europe"],
        u"india": ["asia"],
        u"indonesia": ["asia"],
        u"iran": ["asia"],
        u"iraq": ["asia"],
        u"ireland": ["europe"],
        u"isle of man": ["europe"],
        u"israel": ["asia"],
        u"italy": ["europe"],
        u"jamaica": ["north america"],
        u"japan": ["asia"],
        u"jersey": ["europe"],
        u"jordan": ["asia"],
        u"kazakhstan": ["asia"],
        u"kenya": ["africa"],
        u"kiribati": ["europe"],
        u"north korea": ["asia"],
        u"south korea": ["asia"],
        u"kuwait": ["asia"],
        u"kyrgyzstan": ["asia"],
        u"lao people's democratic republic": ["asia"],
        u"latvia": ["europe"],
        u"lebanon": ["asia"],
        u"lesotho": ["africa"],
        u"liberia": ["africa"],
        u"libya": ["africa"],
        u"liechtenstein": ["europe"],
        u"lithuania": ["europe"],
        u"luxembourg": ["europe"],
        u"macao": ["asia"],
        u"macedonia": ["europe"],
        u"madagascar": ["africa"],
        u"malawi": ["africa"],
        u"malaysia": ["asia"],
        u"maldives": ["asia"],
        u"mali": ["africa"],
        u"malta": ["europe"],
        u"marshall islands": ["europe"],
        u"martinique": ["north america"],
        u"mauritania": ["africa"],
        u"mauritius": ["africa"],
        u"mayotte": ["africa"],
        u"mexico": ["north america"],
        u"federated states of micronesia": ["oceania"],
        u"moldova, republic of": ["europe"],
        u"monaco": ["europe"],
        u"mongolia": ["asia"],
        u"montenegro": ["europe"],
        u"montserrat": ["north america"],
        u"morocco": ["africa"],
        u"mozambique": ["africa"],
        u"myanmar": ["asia"],
        u"namibia": ["africa"],
        u"nauru": ["oceania"],
        u"nepal": ["asia"],
        u"netherlands": ["europe"],
        u"new caledonia": ["oceania"],
        u"new zealand": ["oceania"],
        u"nicaragua": ["north america"],
        u"niger": ["africa"],
        u"nigeria": ["africa"],
        u"niue": ["oceania"],
        u"norfolk island": ["oceania"],
        u"northern mariana islands": ["oceania"],
        u"norway": ["europe"],
        u"oman": ["asia"],
        u"pakistan": ["asia"],
        u"palau": ["asia"],
        u"palestine, state of": ["asia"],
        u"panama": ["north america"],
        u"papua new guinea": ["oceania"],
        u"paraguay": ["south america"],
        u"peru": ["south america"],
        u"philippines": ["asia"],
        u"pitcairn": ["oceania"],
        u"poland": ["europe"],
        u"portugal": ["europe"],
        u"puerto rico": ["north america"],
        u"qatar": ["asia"],
        u"romania": ["europe"],
        u"rwanda": ["africa"],
        u"réunion": ["africa"],
        u"saint barthélemy": ["north america"],
        u"saint kitts and nevis": ["north america"],
        u"saint lucia": ["north america"],
        u"saint martin (french part)": ["north america"],
        u"saint pierre and miquelon": ["north america"],
        u"saint vincent and the grenadines": ["north america"],
        u"samoa": ["oceania"],
        u"san marino": ["europe"],
        u"sao tome and principe": ["africa"],
        u"saudi arabia": ["asia"],
        u"senegal": ["africa"],
        u"serbia": ["europe"],
        u"seychelles": ["africa"],
        u"sierra leone": ["africa"],
        u"singapore": ["asia"],
        u"sint maarten (dutch part)": ["north america"],
        u"slovakia": ["europe"],
        u"slovenia": ["europe"],
        u"solomon islands": ["oceania"],
        u"somalia": ["africa"],
        u"south africa": ["africa"],
        u"south sudan": ["africa"],
        u"sri lanka": ["asia"],
        u"sudan": ["africa"],
        u"suriname": ["south america"],
        u"svalbard and jan mayen": ["europe"],
        u"swaziland": ["africa"],
        u"sweden": ["europe"],
        u"switzerland": ["europe"],
        u"syria": ["asia"],
        u"taiwan": ["asia"],
        u"tajikistan": ["asia"],
        u"tanzania": ["africa"],
        u"thailand": ["asia"],
        u"timor-leste": ["asia"],
        u"togo": ["africa"],
        u"tokelau": ["oceania"],
        u"tonga": ["oceania"],
        u"trinidad and tobago": ["north america"],
        u"tunisia": ["africa"],
        u"turkmenistan": ["asia"],
        u"turks and caicos islands": ["north america"],
        u"tuvalu": ["oceania"],
        u"uganda": ["africa"],
        u"ukraine": ["europe"],
        u"united arab emirates": ["asia"],
        u"united kingdom": ["europe"],
        u"united states minor outlying islands": ["oceania"],
        u"uruguay": ["south america"],
        u"uzbekistan": ["asia"],
        u"vanuatu": ["oceania"],
        u"venezuela": ["south america"],
        u"vietnam": ["asia"],
        u"virgin islands, british": ["north america"],
        u"virgin islands, u.s.": ["north america"],
        u"wallis and futuna": ["oceania"],
        u"western sahara": ["africa"],
        u"yemen": ["asia"],
        u"zambia": ["africa"],
        u"zimbabwe": ["africa"],
        u"åland islands": ["europe"],
    },
    "continent":{}
}

def main():
    for k,v in kl["continent"].iteritems():
        if v not in real_continents and v != "None":
            print k,v

    for k,v in kl["country"].iteritems():
        if v not in iso_countries and v != "None":
            print k,v
