# -*- coding: UTF-8 -*-

# http://rs.gbif.org/vocabulary/gbif/rank.xml
acceptable = {
    u"domain",
    u"kingdom",
    u"subkingdom",
    u"superphylum",
    u"phylum",
    u"subphylum",
    u"superclass",
    u"class",
    u"subclass",
    u"supercohort",
    u"cohort",
    u"subcohort",
    u"superorder",
    u"order",
    u"suborder",
    u"infraorder",
    u"superfamily",
    u"family",
    u"subfamily",
    u"tribe",
    u"subtribe",
    u"genus",
    u"subgenus",
    u"section",
    u"subsection",
    u"series",
    u"subseries",
    u"speciesAggregate",
    u"species",
    u"subspecificAggregate",
    u"subspecies",
    u"variety",
    u"subvariety",
    u"form",
    u"subform",
    u"cultivarGroup",
    u"cultivar",
    u"strain",
}



mapping = {
    u"aberration": None,
    u"accipitriformes": None,
    u"actiniaria": None,
    u"agnostida": None,
    u"alcyonacea": None,
    u"altiverruca": None,
    u"amiiformes": None,
    u"ampelisca": None,
    u"ampeliscidae": None,
    u"amphipoda": None,
    u"anguilliformes": None,
    u"animalia": None,
    u"anseriformes": None,
    u"antipatharia": None,
    u"anura": None,
    u"apodiformes": None,
    u"archaeocopida": None,
    u"arcoida": None,
    u"artiodactyla": None,
    u"atheriniformes": None,
    u"atlantapseudes": None,
    u"aulopiformes": None,
    u"baccata": None,
    u"beryciformes": None,
    u"bonnierell": None,
    u"brisingida": None,
    u"bucerotiformes": None,
    u"byblis": None,
    u"caenogastropoda": None,
    u"calanoida": None,
    u"caprimulgiformes": None,
    u"captorhinida": None,
    u"carnivora": None,
    u"caryophyllales": None,
    u"caudata": None,
    u"cear'a": None,
    u"cetacea": None,
    u"cete": None,
    u"cf.": None,
    u"characiformes": None,
    u"charadriiformes": None,
    u"cheirimedon": None,
    u"chimaeriformes": None,
    u"chiroptera": None,
    u"cimolesta": None,
    u"clade": None,
    u"cladoselachiformes": None,
    u"class": u"class",
    u"classe": u"class",
    u"clupeiformes": None,
    u"coleoptera": None,
    u"columbiformes": None,
    u"condylarthra": None,
    u"coraciiformes": None,
    u"creodonta": None,
    u"crocodylia": None,
    u"cuculiformes": None,
    u"cultivar": u"cultivar",
    u"cyclaspis": None,
    u"cypriniformes": None,
    u"cyprinodontiformes": None,
    u"decapoda": None,
    u"dermoptera": None,
    u"deutella": None,
    u"didelphimorphia": None,
    u"diptera": None,
    u"division": u"phylum",
    u"echinoida": None,
    u"esociformes": None,
    u"espècie": u"species",
    u"espécie": u"species",
    u"f.": u"form",
    u"falconiformes": None,
    u"family": u"family",
    u"famìlia": u"family",
    u"ferruginea": None,
    u"fm.": u"family",
    u"fma.": u"family",
    u"forcipulatida": None,
    u"form": u"form",
    u"form.": u"form",
    u"forma": u"form",
    u"foscae": None,
    u"gadiformes": None,
    u"galliformes": None,
    u"gasterosteiformes": None,
    u"gaviiformes": None,
    u"genero": u"genus",
    u"genuinus": u"genus",
    u"genus or species": None,
    u"genus": u"genus",
    u"gorgonacea": None,
    u"gruiformes": None,
    u"gínero": u"genus",
    u"hadromerida": None,
    u"harpacticoida": None,
    u"hesperornithiformes": None,
    u"heteronemertea": None,
    u"hippuritoida": None,
    u"holotype": None,
    u"hybrid fam": u"family",
    u"hybrid gen": u"genus",
    u"hybrid sp": u"species",
    u"hybrid ssp": u"subspecies",
    u"hybrid": u"species",
    u"hygrophila": None,
    u"hymenopenaeus": None,
    u"hyolithida": None,
    u"hypodigm": None,
    u"hypotype": None,
    u"ichthyodectiformes": None,
    u"ichthyornithiformes": None,
    u"incertae sedis": None,
    u"infr.": u"subspecies",
    u"infraorder": u"suborder",
    u"infraspecificepithet": u"subspecies",
    u"insectivore indet.": None,
    u"insectivore? indet.": None,
    u"isopoda": None,
    u"kingdom": u"kingdom",
    u"lagomorpha": None,
    u"lepechinella": None,
    u"lepidoptera": None,
    u"leptophoxoides": None,
    u"leucothoe": None,
    u"lingulida": None,
    u"littorinimorpha": None,
    u"lophiiformes": None,
    u"megaloptera": None,
    u"megamphopus": None,
    u"multituberculata": None,
    u"munida": None,
    u"musophagiformes": None,
    u"myctophiformes": None,
    u"myersius": None,
    u"myodocopina": None,
    u"myoida": None,
    u"mytiloida": None,
    u"myxiniformes": None,
    u"nektaspida": None,
    u"neogastropoda": None,
    u"nothospecies": u"species",
    u"nothosubsp.": u"subspecies",
    u"notoungulata": None,
    u"nthmorph.": None,
    u"nuculoida": None,
    u"nudibranchia": None,
    u"obtusiloba": None,
    u"odonata": None,
    u"on": None,
    u"onychodontiformes": None,
    u"ordem": u"order",
    u"order": u"order",
    u"ornithischia": None,
    u"osmeriformes": None,
    u"osteoglossiformes": None,
    u"pachycormiformes": None,
    u"palaeonisciformes": None,
    u"passeriformes": None,
    u"paxillosida": None,
    u"pelecaniformes": None,
    u"pennatulacea": None,
    u"pentamerida": None,
    u"perciformes": None,
    u"percopsiformes": None,
    u"perissodactyla": None,
    u"petromyzontiformes": None,
    u"phylum": u"phylum",
    u"phyluym": u"phylum",
    u"phylym": u"phylum",
    u"piciformes": None,
    u"pl-hypotype": None,
    u"platyasterida": None,
    u"pleuronectiformes": None,
    u"poales": None,
    u"poecilosclerida": None,
    u"polymixiiformes": None,
    u"praecardioida": None,
    u"primates": None,
    u"procellariiformes": None,
    u"procreodi": None,
    u"productida": None,
    u"prownbens": None,
    u"pseudericthonius": None,
    u"pseudharpinia": None,
    u"pseudischyrocerus": None,
    u"pterosauria": None,
    u"ptyctodontida": None,
    u"rajiformes": None,
    u"rodentia": None,
    u"rosales": None,
    u"rugosa": None,
    u"salmoniformes": None,
    u"santalales": None,
    u"saurischia": None,
    u"sauropterygia": None,
    u"scleractinia": None,
    u"scorpaeniformes": None,
    u"siluriformes": None,
    u"soricomorpha": None,
    u"sparassodonta": None,
    u"specie": u"species",
    u"species": u"species",
    u"specificepithet": u"species",
    u"spinulosida": None,
    u"spp.": u"subspecies",
    u"squaliformes": None,
    u"squamata": None,
    u"ssp": u"subspecies",
    u"ssp.": u"subspecies",
    u"stolidobranchia": None,
    u"stomiiformes": None,
    u"strigiformes": None,
    u"stromatoporoidea": None,
    u"stylommatophora": None,
    u"sub-gínero": u"subgenus",
    u"subclass": u"subclass",
    u"subdivision": u"subphylum",
    u"subespècie": u"subspecies",
    u"subespécie": u"subspecies",
    u"subfamily": u"subfamily",
    u"subforma": u"subform",
    u"subgenus": u"subgenus",
    u"subkingdom": u"subkingdom",
    u"suborder": u"suborder",
    u"subphylum": u"subphylum",
    u"subsp": u"subspecies",
    u"subsp.": u"subspecies",
    u"subspecies": u"subspecies",
    u"subtropicalis": None,
    u"subvariety": u"subvariety",
    u"suliformes": None,
    u"superclass": u"superclass",
    u"superdivision": u"superphylum",
    u"superfamily": u"superfamily",
    u"superorder": u"superorder",
    u"tabulata": None,
    u"temnospondyli": None,
    u"terebellida": None,
    u"thecodontia": None,
    u"thoracica": None,
    u"tribe": u"tribe",
    u"tribo": u"tribe",
    u"undefinable": None,
    u"undetermined": None,
    u"unionoida": None,
    u"unnamed": None,
    u"valvatida": None,
    u"var": u"variety",
    u"var.": u"variety",
    u"varietas": u"variety",
    u"variety": u"variety",
    u"veneroida": None,
    u"verum": None,
    u"waptiida": None,
    u"zeiformes": None,
    u"zoanthidea": None,
    u"||||": None,
    u"|||||": None,
    u"||||||||": None,
    u"|||||||||||||||||||||||||||||||||||||": None,
    u"×": None,
}

def main():
    new_accept_set = set()
    # new_accept_set |= acceptable

    import requests
    import json

    r = requests.get("http://search.idigbio.org/v2/summary/top/records?top_fields=[%22taxonrank%22]&count=1000")
    o = r.json()
    for k in o["taxonrank"]:
        if k not in mapping:
            print k, o["taxonrank"][k]
        elif mapping[k] is None:
            pass
        elif mapping[k] not in acceptable:
            print k, mapping[k]
            new_accept_set.add(mapping[k])

    if len(new_accept_set) > 0:
        print json.dumps(list(new_accept_set), indent=4)


    
if __name__ == '__main__':
    main()