acceptable_licenses_trans = {
    "http://creativecommons.org/licenses/by-nc-sa/4.0/": "CC4 BY-NC-SA",
    "http://creativecommons.org/licenses/by-sa/4.0/": "CC4 BY-SA",
    "http://creativecommons.org/licenses/by-nc/4.0/": "CC4 BY-NC",
    "http://creativecommons.org/licenses/by/4.0/": "CC4 BY",
    "http://creativecommons.org/licenses/by-nc-sa/3.0/": "CC3 BY-NC-SA",
    "http://creativecommons.org/licenses/by-sa/3.0/": "CC3 BY-SA",
    "http://creativecommons.org/licenses/by-nc/3.0/": "CC3 BY-NC",
    "http://creativecommons.org/licenses/by/3.0/": "CC3 BY",
    "http://creativecommons.org/publicdomain/zero/1.0/": "CC0",
    "https://creativecommons.org/licenses/by-nc-sa/4.0/": "CC4 BY-NC-SA",
    "https://creativecommons.org/licenses/by-sa/4.0/": "CC4 BY-SA",
    "https://creativecommons.org/licenses/by-nc/4.0/": "CC4 BY-NC",
    "https://creativecommons.org/licenses/by/4.0/": "CC4 BY",
    "https://creativecommons.org/licenses/by-nc-sa/3.0/": "CC3 BY-NC-SA",
    "https://creativecommons.org/licenses/by-sa/3.0/": "CC3 BY-SA",
    "https://creativecommons.org/licenses/by-nc/3.0/": "CC3 BY-NC",
    "https://creativecommons.org/licenses/by/3.0/": "CC3 BY",
    "https://creativecommons.org/publicdomain/zero/1.0/": "CC0",
    "http://creativecommons.org/licenses/by-nc-sa/4.0": "CC4 BY-NC-SA",
    "http://creativecommons.org/licenses/by-sa/4.0": "CC4 BY-SA",
    "http://creativecommons.org/licenses/by-nc/4.0": "CC4 BY-NC",
    "http://creativecommons.org/licenses/by/4.0": "CC4 BY",
    "http://creativecommons.org/licenses/by-nc-sa/3.0": "CC3 BY-NC-SA",
    "http://creativecommons.org/licenses/by-sa/3.0": "CC3 BY-SA",
    "http://creativecommons.org/licenses/by-nc/3.0": "CC3 BY-NC",
    "http://creativecommons.org/licenses/by/3.0": "CC3 BY",
    "http://creativecommons.org/publicdomain/zero/1.0": "CC0",
    "https://creativecommons.org/licenses/by-nc-sa/4.0": "CC4 BY-NC-SA",
    "https://creativecommons.org/licenses/by-sa/4.0": "CC4 BY-SA",
    "https://creativecommons.org/licenses/by-nc/4.0": "CC4 BY-NC",
    "https://creativecommons.org/licenses/by/4.0": "CC4 BY",
    "https://creativecommons.org/licenses/by-nc-sa/3.0": "CC3 BY-NC-SA",
    "https://creativecommons.org/licenses/by-sa/3.0": "CC3 BY-SA",
    "https://creativecommons.org/licenses/by-nc/3.0": "CC3 BY-NC",
    "https://creativecommons.org/licenses/by/3.0": "CC3 BY", 
    "https://creativecommons.org/publicdomain/zero/1.0": "CC0",    
    "by-nc-sa": "CC4 BY-NC-SA",
    "by-sa": "CC4 BY-SA",
    "by-nc": "CC4 BY-NC",
    "by": "CC4 BY",
    "CC BY-NC-SA": "CC4 BY-NC-SA",
    "CC BY-SA": "CC4 BY-SA",
    "CC BY-NC": "CC4 BY-NC",
    "CC BY": "CC4 BY",
    "CC-BY-NC-SA": "CC4 BY-NC-SA",
    "CC-BY-SA": "CC4 BY-SA",
    "CC-BY-NC": "CC4 BY-NC",
    "CC-BY": "CC4 BY",
    "CC0": "CC0",    
    "CC BY-NC-SA (Attribution-NonCommercial-ShareAlike)": "CC4 BY-NC-SA",
    "CC BY-SA (Attribution-ShareAlike)": "CC4 BY-SA",
    "CC BY-NC (Attribution-NonCommercial)": "CC4 BY-NC",
    "CC BY-NC (Attribution-Non-Commercial)": "CC4 BY-NC",
    "CC BY (Attribution)": "CC4 BY",
    "CC0 1.0 (Public-domain)": "CC0",  
    "Public Domain": "Public Domain",

    "Attribution-NonCommercial-ShareAlike 4.0 International": "CC4 BY-NC-SA",
    "URL: http://creativecommons.org/licenses/by-nc-sa/4.0/": "CC4 BY-NC-SA",
    "Creative Commons Attribution Non-Commercial (CC BY-NC)": "CC4 BY-NC",
    "Attribution-NonCommercial-ShareAlike CC BY-NC-SA 4.0": "CC4 BY-NC-SA",
    "This work is licensed under a Creative Commons CCZero 1.0 License http://creativecommons.org/publicdomain/zero/1.0/legalcode.": "CC0",
    "http://creativecommons.org/publicdomain/zero/1.0/ http://www.vertnet.org/resources/norms.html": "CC0",
    "http://creativecommons.org/publicdomain/zero/1.0 and http://vertnet.org/resources/norms.html": "CC0",
    "This work is licensed under a Creative Commons CCZero 1.0 License. http://creativecommons.org/publicdomain/zero/1.0/": "CC0",
    "This work is licensed under a Creative Commons CCZero 1.0 License http://creativecommons.org/publicdomain/zero/1.0/legalcode.": "CC0",
    "This work is licensed under a Creative Commons CCZero 1.0 License http://creativecommons.org/publicdomain/zero/1.0/legalcode": "CC0",
    "Tall Timbers data is governed by the Creative Commons Attribution 3.0 license (http://creativecommons.org/licenses/by/3.0/legalcode). Any use of data or images must be attributed to Tall Timbers Research Station and Land Conservancy.": "CC3 BY",
    "http://creativecommons.org/licenses/by/4.0/deed.en_US and http://biodiversity.ku.edu/research/university-kansas-biodiversity-institute-data-publication-and-use-norms": "CC4 BY",

    '<a href="http://creativecommons.org/licenses/by-nc-sa/3.0/us/" rel="license">  <img src="http://i.creativecommons.org/l/by-nc-sa/3.0/us/88x31.png" style="border-width: 0pt;" alt="Creative Commons License"/>  </a>': "CC3 BY-NC-SA",
    '<a href="http://creativecommons.org/licenses/by-nc-sa/3.0/us/" rel="license"> <img src="http://i.creativecommons.org/l/by-nc-sa/3.0/us/88x31.png" style="border-width: 0pt;" alt="Creative Commons License"/> </a>': "CC3 BY-NC-SA",
    '<a href="http://creativecommons.org/licenses/by-nc-sa/3.0/us/" rel="license"> <img src="http://i.creativecommons.org/l/by-nc-sa/3.0/us/88x31.png" style="border-width: 0pt;" alt="Creative Commons License"/></a>': "CC3 BY-NC-SA",
    '<a href="http://creativecommons.org/licenses/by-nc-sa/3.0/us/" rel="license"><img src="http://i.creativecommons.org/l/by-nc-sa/3.0/us/88x31.png" style="border-width: 0pt;" alt="Creative Commons License"/></a>': "CC3 BY-NC-SA",
    '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/"> <img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png" /> </a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/">Creative Commons Attribution-ShareAlike-Non Commercial 3.0 Unported License</a>.': "CC3 BY-NC-SA",
    '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/">Creative Commons Attribution-ShareAlike-Non Commercial 3.0 Unported License</a>.': "CC3 BY-NC-SA",
    '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/us/">  <img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/us/88x31.png" />  </a>': "CC3 BY-NC-SA",
    '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/us/"> <img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/us/88x31.png" /> </a>': "CC3 BY-NC-SA",
    '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/us/"> <img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/us/88x31.png" /></a>': "CC3 BY-NC-SA",
    '<a rel="license" href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons Attribution 3.0 License"><img src="http://i.creativecommons.org/l/by/3.0/88x31.png" alt="License"></a>': "CC3 BY",
    '<a rel="license" href="http://creativecommons.org/licenses/by/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by/3.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/3.0/">Creative Commons Attribution 3.0 Unported License</a>.': "CC3 BY",
    '<a rel="license" href="http://creativecommons.org/licenses/publicdomain/">  <img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/publicdomain/88x31.png" />  </a>': "Public Domain",
    '<a rel="license" href="http://creativecommons.org/publicdomain/mark/1.0/"><img src="http://i.creativecommons.org/p/mark/1.0/88x31.png"     style="border-style: none;" alt="Public Domain Mark" /></a><br />This work is free of known copyright restrictions.': "Public Domain",
    '<a rel="license" href="http://creativecommons.org/publicdomain/zero/1.0/">      <img src="http://i.creativecommons.org/p/zero/1.0/88x31.png" style="border-style: none;" alt="CC0" />    </a>': "Public Domain",
    '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/"> <img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png" /> </a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-n': "CC3 BY-NC-SA",
    '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-': "CC3 BY-NC-SA",
    '<a rel="license" href="http://creativecommons.org/licenses/by/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by/3.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/3.0/">Creative': "CC3 BY",

}

licenses = {
    "CC4 BY-NC-ND": {
        "rights": "BY-NC-ND",
        "logourl": "https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png",
        "webstatement": "http://creativecommons.org/licenses/by-nc-nd/4.0/",
    },
    "CC4 BY-ND": {
        "rights": "BY-ND",
        "logourl": "https://i.creativecommons.org/l/by-nd/4.0/88x31.png",
        "webstatement": "http://creativecommons.org/licenses/by-nd/4.0/",
    },    
    "CC4 BY-NC-SA": {
        "rights": "BY-NC-SA",
        "logourl": "https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png",
        "webstatement": "http://creativecommons.org/licenses/by-nc-sa/4.0/",
    },
    "CC4 BY-SA": {
        "rights": "BY-SA",
        "logourl": "https://i.creativecommons.org/l/by-sa/4.0/88x31.png",
        "webstatement": "http://creativecommons.org/licenses/by-sa/4.0/",
    },
    "CC4 BY-NC": {
        "rights": "BY-NC",
        "logourl": "https://i.creativecommons.org/l/by-nc/4.0/88x31.png",
        "webstatement": "http://creativecommons.org/licenses/by-nc/4.0/",
    },
    "CC4 BY": {
        "rights": "BY",
        "logourl": "https://i.creativecommons.org/l/by/4.0/88x31.png",
        "webstatement": "http://creativecommons.org/licenses/by/4.0/",
    },
    "CC3 BY-NC-ND": {
        "rights": "BY-NC-ND",
        "logourl": "https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png",
        "webstatement": "http://creativecommons.org/licenses/by-nc-nd/4.0/",
    },
    "CC3 BY-ND": {
        "rights": "BY-ND",
        "logourl": "https://i.creativecommons.org/l/by-nd/4.0/88x31.png",
        "webstatement": "http://creativecommons.org/licenses/by-nd/4.0/",
    },    
    "CC3 BY-NC-SA": {
        "rights": "BY-NC-SA",
        "logourl": "http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png",
        "webstatement": "http://creativecommons.org/licenses/by-nc-sa/3.0/",
    },
    "CC3 BY-SA": {
        "rights": "BY-SA",
        "logourl": "http://i.creativecommons.org/l/by-sa/3.0/88x31.png",
        "webstatement": "http://creativecommons.org/licenses/by-sa/3.0/",
    },
    "CC3 BY-NC": {
        "rights": "BY-NC",
        "logourl": "http://i.creativecommons.org/l/by-nc/3.0/88x31.png",
        "webstatement": "http://creativecommons.org/licenses/by-nc/3.0/",
    },
    "CC3 BY": {
        "rights": "BY-NC-SA",
        "logourl": "http://i.creativecommons.org/l/by/3.0/88x31.png",
        "webstatement": "http://creativecommons.org/licenses/by/3.0/",
    },
    "CC0": {
        "rights": "CC0",
        "logourl": "http://i.creativecommons.org/p/zero/1.0/88x31.png",
        "webstatement": "http://creativecommons.org/publicdomain/zero/1.0/",
    },
    "Public Domain": {
        "rights": "Public Domain",
    }
}